hashicorp/vscode-terraform

syntaxes/terraform.tmLanguage

Previously, the terraform plugin for vscode only recognized resources starting with the keyword `resource`. But in Terraform 0.7.x, a new resource type `data` was introduced. This is a naive implementation to support that.
Note that while I'm using this locally, I have not tested this thoroughly, so this PR is more of an invitation to complete this work. There may be unique syntax for the `data` resources that this admittedly simple change doesn't account for.

Recognize "data" resources.

---

terraform.configuration.json

This tells vscode that the single line comment is prefixed with a `#` instead of a `//`. The double-slash comment does appear to work, but:
a) it does not show up in the [official documentation](https://www.terraform.io/docs/configuration/syntax.html).
b) it is not syntax highlighted, but `#` comments are.
This is useful for automated block commenting and uncommenting in vscode with `ctrl+/`, which will use the wrong kind of comments until this is merged.

Updates the the line comment to hash instead of double-slash

---

.gitignore
package.json
src/extension.ts
test/extension.test.ts
test/index.ts
tsconfig.json

I added a configuration option for `terraform.formatOnSave` and a little function running `terraform fmt -` with the input from the document.
Thoughts?

Added very basic terraform fmt runner

---

terraform.configuration.json

This enables automatic quotes and other characters completion, as well
as the surrounding pair feature that allows selecting a word and putting
it inside brackets or quotes, for example.

Add auto closing and surrounding pairs

---

syntaxes/terraform.json

Terraform 0.10.4 introduced local variables with [documentation here](https://www.terraform.io/docs/configuration/locals.html).
This adds syntax support for keywords `local` and `locals`.

Add support for local variable type

---

src/validate.ts

Make the output easy to find for users. I had a frustrating time finding the validation output (like in #34). This change highlights the output channel containing the validation warnings.
The previous behavior requires the user to find the 'Terraform' entry in the output pane's dropdown. This wasn't obvious to me.

Show output channel on validation fail

---

src/format.ts
src/lint.ts
src/process.ts
src/validate.ts

Hi,
I placed `tflint.exe` in the directory that it contain some spaces (as like as `C:\Program Files`),
it is not work.
I replaced some `child_process.exec` to `child_process.execFile` to fix.

Change child_process.exec to child_process.execFile.

---

src/autocompletion/completion-provider.ts

Looks like after some of the latest changes the autocompletion seems to be completely broken for me. I've seen autocomplete working somewhat well on a machine I have no access to at the moment, but I'm not sure what version it was running (not latest for sure).
I tried to test v1.0.5 (VSCode v1.23.0) that currently is the latest stable and it was still failing to me, so I dug in to see what was going on.
This MR addresses lookup of variables and outputs in the Index.
I still seem to experience issues with the rest of the autocomplete (resources, etc)

Fix autocomplete of variables and outputs

---

syntaxes/terraform.json

@mauve This should fix #89 
As a reference, it uses https://manual.macromates.com/en/language_grammars but written in JSON for some reason.
Basically regex for `^\s*(})` 
Intention:
- Match any `}` starting with 0 or more whitespaces
- It will not match if the `}` is not on a newline (as its not correct syntax anyway)
- Will match `}` for all resources.
AFAIK there is no way to match multi-line so I cant do a selector for all `{}` pairs and be done.

Add matching syntax for closing brackets

---

language-configuration.json

@mauve This should enable brackets autoclosing  to work with a new `Auto Closing Brackets` settings set to `languageDefined`
Ref: https://github.com/Microsoft/vscode/pull/52634

Allow brackets auto-closing in double quote strings

---

src/autocompletion/section-completions.ts

Fixes cursor location for `value` under `variableWithDocumentationAndValueCompletion`.
Currently the `description` placeholder and cursor are copied under the `default` section.

Fix variable autocomplete default placeholder

---

syntaxes/terraform.json

For #157 (but doesn't close it)
I have had a go at improving the syntax highlighting for Terraform 0.12 and beyond. I probably haven't fixed every case, but this should make it better especially for type definitions, expressions and function calls.
NOTE: this will not fix the erroneous syntax errors, but it will at least make the coloring better.
Also NOTE: this is my first time ever contributing to the project or any open source project, so please review closely, and let me know if I have done anything wrong.

Update syntax highlighting to better support terraform 0.12

---

.hashibot.hcl

This matches a tested configuration from the language server repo, except that it has `+10min` on the cron schedule, just to help the spread (and avoid any congestion either in form of load or API usage).
This does the following:
- lock _closed_ PRs and issues after 30 days
- close issues which have been labelled as `stale` or `waiting-response` and haven't received response for 90 days
- so just for avoidance of doubts the closing "timer" still needs to be started by a human (maintainer) adding the label and the bot will not close any issues without that label

Add Hashibot configuration

---

README.md

RE: https://github.com/hashicorp/vscode-terraform/issues/329
This PR simply adds documentation for 2 common issues for users when they are getting started:
```
* Multi-folder workspaces are not yet supported. ([info](https://github.com/hashicorp/vscode-terraform/issues/329#issuecomment-639378948))
* Single-folder workspaces in which the root module is not the top-level folder are not supported. ([info](https://github.com/hashicorp/vscode-terraform/issues/329#issuecomment-639107179))
```

add Known Issues section to README

---

README.md

Looks like this was just a relic from the older version of the extension. Generally `hcl` represents generic HCL configuration, not something Terraform would ever load.
That said it's something we may consider supporting in the future either directly or via a separate extension and/or separate language server.
For now _not_ supporting HCL in a _Terraform_ extension is intentional.
Relatedly if any other Terraform extension supports HCL and treats it the same way as Terraform's HCL, it's _probably_ inaccurate. Many extensions aren't currently aware of this distinction and that's something we also need to communicate going forward, as per https://github.com/hashicorp/terraform-ls/issues/50#issuecomment-630053301

Readme: Correct supported list of extensions

---

syntaxes/terraform.tmGrammar.json

Signed-off-by: Anthony Sottile <asottile@umich.edu>
this was crashing my text editor with something like this:
```terraform
resource "a" "a" {
b = ()
}
```
```console
$ babi t.tf
Traceback (most recent call last):
File "/home/asottile/bin/babi", line 8, in <module>
sys.exit(main())
File "/home/asottile/opt/venv/lib/python3.8/site-packages/babi/main.py", line 152, in main
return c_main(stdscr, filenames, positions, stdin, perf)
File "/home/asottile/opt/venv/lib/python3.8/site-packages/babi/main.py", line 57, in c_main
res = _edit(screen, stdin)
File "/home/asottile/opt/venv/lib/python3.8/site-packages/babi/main.py", line 29, in _edit
screen.draw()
File "/home/asottile/opt/venv/lib/python3.8/site-packages/babi/screen.py", line 258, in draw
self.file.draw(self.stdscr, self.margin)
File …
```

fix parenthesis inclusion

---

README.md
package.json
src/extension.ts

waiting for PR: https://github.com/hashicorp/terraform-ls/pull/251

add configuration for exclude root module

---

src/languageServerInstaller.ts

This fixes #521
I'm guessing there won't be a native build of terraform-ls until at least February 2021 when Golang 1.16 is released with `GOARCH=arm64` support. So it seems worth doing this for now, the amd64 terraform-ls binary works great.

use the amd64 binary on Apple Silicon Macs for now

---

src/languageServerInstaller.ts

This will allow installation of solaris builds and `linux/arm64` when it's published: https://github.com/hashicorp/terraform-ls/pull/351

Extract Go/NodeJS OS/arch translation logic

---

.gitignore
src/languageServerInstaller.ts

This change makes the extension leverage a new flag introduced in LS 0.13.0 via https://github.com/hashicorp/terraform-ls/pull/386 so that we can merge and release https://github.com/hashicorp/terraform-ls/pull/407
The usual disclaimer of my TS/JS skills applies here - i.e. any criticism is welcomed 😄

Use version JSON output of LS during installation

---

src/extension.ts
src/languageServerInstaller.ts

Improve error message for failed language server install

---

src/languageServerInstaller.ts

The AppInsights dashboard doesn't make it clear where "version" is coming from when it appears in the filter options, so changing the name will make it more obvious where the value is coming from.

Change telemetry value for the language server version

---

CHANGELOG.md
README.md

Terraform-LS repo has deleted master, so redirects to the default of main. 
Vscode-terraform still has the master branch, so the links from VSCode readme take you to the old changelog, not the updated one on the main branch.

Fix branch links for terraform-ls and vscode-terraform in readme and changelog

---

src/extension.ts
src/languageServerInstaller.ts

Check for language server updates every 24 hours

---

syntaxes/terraform.tmGrammar.json

Closes #603
I fixed another small (but recurrent) bug while I was in there, which is on the second commit.

Update syntax highlighting for Terraform 0.15

---

CHANGELOG.md

Changed the incorrect years from `2020` to `2021` for the last 3 versions.

Update incorrect dates to CHANGELOG.md

---

.github/workflows/test.yml
package-lock.json
package.json
src/extension.ts
src/languageServerInstaller.ts
src/test/helper.ts
src/test/runTest.ts
src/test/workspaces.test.ts

The GPG key used to sign the package signature files has been rotated per [HCSEC-2021-12](https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512). This update will allow to continue validating `terraform-ls` packages as part of the install process.
Closes #611

Update js-releases dep to resolve security issue

---

src/extension.ts

Partially fixes #618 
Previously PR 595 added in a periodic check for the language server version
however the period chosen was incorrect. Currently it checks evey 24mins,
not 24 hours.
This commit changes the period to the expected 24hr period.

Correct delay for language server version check

---

syntaxes/terraform.tmGrammar.json

This PR reorders the built-in functions to put `abspath` before `abs` to prioritize this in highlighting. It appears that the highlighting for `abspath` was being split between the built-in function `abs` and the reference `path`. This is a fix for #629.

Reorder functions to prioritize abspath highlight (#629)

---

src/extension.ts
src/utils.ts

Relates to #618 
Previously the extension would trigger a new auto-update whenever it was
activated. However this can causes issues when a user deactivates-activates the
language server quickly multiple times, as it cause multiple timeouts to be
created. Additionally, when disabled, it would not clear any active timeouts.
This commit adds a small wrapper around the setTimeout function to track usage.
In particular, it will silently ignore calls to add a timeout if a timeout is
already active.  This commit also clears any timeouts when the language server
is disabled.

Only trigger auto-update once in a VSCode session

---

package.json

No particular reason, just "cleaning up" before the release.

Bump npm requirement to 7.17.0 (latest major)

---

.github/workflows/test.yml
package.json
src/clientHandler.ts
src/extension.ts
src/test/workspaces.test.ts

Fixes #685 
This bug was introduced in 2.12.0 and affects any folders within workspaces of multiple folders which are not descendants of the 1st folder in the workspace.
For example, if workspace has two folders, and
- 1st one `/my-repo` and 2nd `/my-repo/subfolder` then that workspace is **not** affected by the bug
- 1st one `/my-repo` and 2nd `/another-repo` then that workspace **is** affected by the bug
The bug affects only users on language server `0.19+` (which is the first version that supports multiple folders natively).
Prior to this patch we would always launch the first instance of a client/server, to obtain the server capabilities and see if the server supports multiple folders. We would then continue launching more instances for any more folders if it doesn't, or reuse the …

Fix DocumentSelector for multi-folder workspace

---

src/clientHandler.ts
src/extension.ts

This PR includes two fixes:
As part of the refactoring and fixing a different bug in #688 I didn't notice that the `updateLanguageServer` was previously argument-less function and it is still passed as such into the update time ticker, despite needing two arguments.
This leads to the following error popup every time an update is attempted (every 24 hours):
This was only uncovered once LS updates were actually fixed - i.e. users are technically not affected by this as updating isn't hitting the codepath anyway.
Previously `this.getClient()?.client.needsStart()` was used to obtain the client and check if it _needs start_ (meaning if it's not started _yet_) which is actually the opposite of what we need. 🤦🏻 
I instead simplified that to `has()` - which is already used for the individual …

fix language server update logic

---

src/languageServerInstaller.ts
src/test/runTest.ts
src/utils.ts

Unblocks #691 
--- 
This fixes a long undiscovered bug which would cause the LS to never launch
in situation where there is an escapable character (such as whitespace)
in the *default* path leading to the LS binary.
The root cause is string concatenation of full commands (and
`child_process.exec` API expecteding already escaped string)
when checking LS version, instead of passing arguments individually.
This problem would also never be surfaced to the user due to some other
issues with error reporting (that can be addressed in a separate PR).
This affects all v2 versions from what I can tell (based on the codepath).
First time launch after fresh installation (or upgrade) on Windows with account called `Radek Simko` (with whitespace) + empty settings:
After restarting VS Code:

fix: launch LS even if path contains escapable characters

---

src/clientHandler.ts
src/extension.ts
src/languageServerInstaller.ts
src/serverPath.ts
src/utils.ts
src/vscodeUtils.ts

Unblocks #691 
--- 
Path to either the LS binary or to the installation folder is needed in multiple places and sadly isn't as trivial. This extraction ensures that the same mistakes (such as forgetting to reflect Windows exe extensions or path separators) aren't repeated.
Windows would normally still find and execute a binary even without the "exe" extension so this bug shouldn't be affecting Windows users at this point, but some further checks (testing file existence/permissions) will be added in the above PR and that requires knowing the real binary name.

Extract logic for determining LS paths

---

package-lock.json
package.json
src/clientHandler.ts
src/extension.ts
src/serverPath.ts

Depends on #696 
Fixes #681
--- 
As discussed in https://github.com/hashicorp/vscode-terraform/pull/688#discussion_r670994631 we would previously try to communicate conflicting config options via an exception, which was never caught anywhere. In case user happened to set the two conflicting options the server would just (silently) never launch and they wouldn't receive any UI feedback.
With this PR that error is now surfaced correctly as error popup:
--- 
Additionally this PR also improves error handling in cases where path to LS is for some reason wrong or inaccessible. The error surfaced by the upstream library would otherwise look like this:
so we make it **more helpful** by surfacing the real error messages and adding a hint in cases where user has specified the path themselves:

Improve error handling

---

package.json
src/extension.ts
src/languageServerInstaller.ts

Partially solves #628 
This PR does not address any UI for selecting a version pin.  It merely adds all of the plumbing to make the version pin actually work.  A later PR would then add the UI layer.
---
Previously the Language Server would always update to the latest version however
there are scenarios where using an older version is required.  This commit adds
a new `version` configuration setting which is a semver range (as per the
@hashicorp/js-releases module). This setting is then used to find an appropriate
release when calling the Hashi release API.
This commit also adds validation on the `version` setting to ensure it is a
valid string and warns the user of the potentially bad setting.
This commit then updates the Language Server installer to not only upgrade the
server, but also …

(GH-628) Add semver based version pin for Language Server

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

I re-ordered some sections to make it easier to follow/read from top to bottom, added more OS-specific details for how to find versions of things and added a "template" to help understand what's expected under each section.

github: further improve issue templates

---

.github/dependabot.yml

This should help us keep our dependencies up to date.
Initially this would use more "cautious" strategy and only perform updates that can be done in lockfile only, i.e. leaving requirements in the manifest untouched. Later though we can consider relaxing these.

build: Introduce dependabot for updating deps

---

.github/workflows/test.yml

Default timeouts are actually 6 hours and our jobs should typically finish within minutes, so there's no point in waiting any longer.

github: Reduce timeouts

---

.editorconfig
.eslintignore
.eslintrc.json
.gitattributes
.prettierignore
.prettierrc
.vscode/extensions.json
.vscode/settings.json
package-lock.json
package.json

Update eslint and prettier packages and add style and format guidelines to editorconfig and VS Code worskpace settings file.
This aligns to company standards for code style and formatting and ensures consistent spacing, line endings, and file encodings. This does not enable any new eslint rules, as that is out of scope for this line of work.
This also configures VS Code to use prettier and eslint for all typescript, javascript and json formatting and use eslint and prettier to enforce guidelines.

(maint) Set syntax and format style guidelines

---

.vscode/settings.json

This removes excluding node_modules from the file explorer tree in VS Code. Typically node_modules is hidden from search in VS Code as a speed improvement, but hiding it from the treeview is more of a personal preference than a requirement.

Include node_modules in VS Code editor

---

src/clientHandler.ts
src/extension.ts
src/languageServerInstaller.ts
src/serverPath.ts
src/showReferences.ts
src/utils.ts
src/vscodeUtils.ts

Using the prettier and eslint configuration set in 790129a2d41f22afa398230c9c0c87d343d88d0a, this applies all formatting fixes and style changes necessary.
This also converts the spacing for the snippet, syntax and language configuration files to ensure consistent spacing, but does not format the file in order to not change the order of the snippets.
This also formarts the VS Code launch and task json files to cleanup the spacing and line endings.

Align formatting and code style

---

.gitattributes

This is in preparation for automating marketplace publishing, which will run on GitHub-hosted Windows instance.
The original configuration has a few problems:
- every file is treated as text (including files which should be treated as binaries)
- some binary files have their line endings converted after checkout on Windows, which then prevents publishing
```
Run npx -- vsce publish 2.14.1
ERROR  Command failed: npm version 2.14.1
npm ERR! Git working directory not clean.
npm ERR! M terraform-banner.png
npm ERR! M terraform.png
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\npm\cache\_logs\2021-09-15T07_53_35_881Z-debug.log
```

gitattributes: ensure all text files end with LF

---

.github/workflows/test.yml

We generally expect the extension to work with latest stable versions of Terraform, but this gives us more predictability and better reproducible test failures (if any occur).
https://www.npmjs.com/package/semver#ranges

ci: constraint Terraform for testing to `~1.0`

---

package.json

VS Code Extensions are never published as NPM packages, so this prevents any accidental publishing and follows a practice used by Go VS Code extension.
https://github.com/golang/vscode-go/blob/23a2db0dca292ef4e5fdf951d309722eb9529813/package.json#L25

package.json: prevent accidental npm publishing

---

src/clientHandler.ts
src/extension.ts

This is to address a long-term issue which was also spotted in https://github.com/hashicorp/vscode-terraform/pull/771#discussion_r709226812

fix: avoid tracking client which is not ready yet

---

.github/workflows/build.yml
.github/workflows/test.yml

This is to make future updates of Node.js easier, to prepare for automation of Marketplace publishing and also to align version management with what we do in LS and elsewhere:
https://github.com/hashicorp/terraform-ls/blob/356136b9444ecf2274b9d28947f18e8a71f9fd0e/.github/workflows/ci.yml#L70-L90

ci: Read node version from nvmrc

---

.github/workflows/build.yml

This is to address the following failure:
https://github.com/hashicorp/vscode-terraform/actions/runs/1258148142

ci: change windows-style slash to unix-style

---

.npmrc
package-lock.json
package.json
src/test/runTest.ts

This sets the npm lockfile version back to 1, which aligns the npm version to the version of node we target and also updates the vscode-languageclient library to the 7.0.0 release, which requires the minimum vs code engine to be 1.52.0.
We currently use node v14.X as the targeted version, which uses npm v6.X. In commit 8bc325ced2690d55d5e60e16a540b0261949a817 we updated the lockfile to version 2 using npm v7.X. This results in a lockfile mismatch when using node v14.X and npm v6.X to do an `npm install`. While the npm v7.X lockfile is compatible with npm 6, this does produce a warning that the wrong dependency version may be downloaded. A future commit will handle the migration to npm 7 when we move off of node v14.X.
The vscode-languageclient 7.0.0 release is the current supported …

Reset npm lock file version to 1

---

assets/icons/terraform.svg
package.json
src/extension.ts
src/providers/moduleProvider.ts

Module view inside Explorer view container, with nested modules displayed
Documentation Link
Closes #698
Needs https://github.com/hashicorp/terraform-ls/pull/632

Module View Provider

---

.vscode/launch.json
.vscode/tasks.json
package.json

This modifies `launch.json` and `tasks.json` to only run `terraform init` when running the tests through the ExtensionHost. This allows debugging the extension without running terraform each time, taking the total time to start the ExtensionHost from several seconds to less than one.
This also reduces tasks.json task references to npm scripts to one entry for `npm watch` and consolidates the `terraform init` task to one entry.
It also removes the need to have terraform installed just to debug the extension, as the primary reason is to debug is interactions with the language server which doesn't use the binary for most operations.
Fixes #622

Update launch configuration and tasks

---

package.json
src/providers/moduleProvider.ts

This detects whether the currently installed Language Server supports the module calls command before calling the Language Server command. This prevents the provider from throwing an error with a LS that doesn't have the command.

Prevent Module View Provider from failing to call LS

---

package.json
src/clientHandler.ts

This PR adds a new setting called `enableReferenceCountCodeLens` which toggles displaying reference counts above top level blocks and attributes.
Closes #713.

Implement opt out config option for ref count code lens

---

package.json
src/clientHandler.ts

This PR adds support for the new `ignoreDirectoryNames` language server side config option.
Needs https://github.com/hashicorp/terraform-ls/pull/696 to merge.

Add ignoreDirectoryNames setting for language server configuration

---

src/extension.ts

Delays enabling the ModuleProvider until the client has started to avoid the case where the user has the view pane open on editor start but the language client or server has not fully initialized yet.

Fix ModuleProvider starting before client ready

---

src/test/integration/codeAction.test.ts

Enable the CodeAction tests that were commented out until the changes in https://github.com/hashicorp/terraform-ls/pull/680 was released.

Enable CodeAction tests

---

package.json
src/clientHandler.ts

This PR renames the existing `enableReferenceCountCodeLens` setting to a proper vscode one.
Maybe we want to update the `scope` of the setting, too.

Rename codelens setting

---

src/extension.ts
src/providers/moduleProvider.ts
src/test/integration/workspaces.test.ts
src/utils.ts

Fixes warnings in extension activation by strongly typing return value. Safely ignores the rest as they rely on untyped responses.

Fix Warnings

---

.github/workflows/preview.yml
build/nightly.md
build/preview
package.json

This adds a new Github Action that publishes the `hashicorp.terraform-preview` extension to the VS Code Marketplace.
https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform-preview

Publish preview builds

---

CHANGELOG.md
src/clientHandler.ts
src/extension.ts
src/providers/moduleProvider.ts
src/serverPath.ts
src/vscodeUtils.ts

- Refactors ClientHandler to only use one `LanguageClient` per extension activation. Removes the Map of `LanguageClients` and ensures that any attempt to use a `LanguageClient` or method happens after the onReady event finishes. The terraform-ls sever implemented multi-folder/workspace support in hashicorp/terraform-ls#502. This means the VS Code extension no longer needs multiple clients to track how many folders are added to the current workspace and which event for which file needs to be sent at certain times.
- Moves the list of supported commands to a private property of the ClientHandler class and populates it when the client and LS are initialized. Previously you could attempt to ask the server what commands were supported before the client and server had finished the …

Refactor to Single Language Client

---

package.json
src/extension.ts
src/providers/moduleCalls.ts
src/providers/moduleProviders.ts
src/providers/providerProvider.ts

This PR adds a new tree view panel in the explorer menu with the installed providers in the current module.
It depends on the language server PR https://github.com/hashicorp/terraform-ls/pull/712
New panel, listing providers with the installed version:
No providers detected:
Providers not installed (yet):
Tooltip showing the required version:
Closes #701

Add panel for module providers

---

package.json
src/clientHandler.ts
src/languageServerInstaller.ts
src/serverPath.ts

Replaces all usages of the fs package with the vscode.workspace.fs wrapper. This ensures safe usage of the filesystem and allows us in the future to move to remote extension use.
Fix bug where zip is not deleted after extraction. This also helps in the future when we minify the extension and del does not work.
Closes #812

Use vscode.workspace.fs instead of fs package

---

src/extension.ts
src/test/integration/statusBar.test.ts

VSCode always hid the status bar because we never executed the command for getting the module callers as it was missing the `commandPrefix`.

Fix terraform status bar

---

src/clientHandler.ts
src/telemetry.ts

Depends on https://github.com/hashicorp/terraform-ls/pull/681 but the release does _not_ need to be coordinated. Older versions of LS will just ignore the experimental capability.
Regarding documentation, I believe the existing paragraph already reflects the existing situation which won't really change with this PR: https://github.com/hashicorp/vscode-terraform#telemetry

Process telemetry from language server

---

.vscode/tasks.json
src/extension.ts
src/test/integration/workspaces.test.ts

This PR depends on #857, which needs to be merged first.
Our `activate` function returned `moduleCallers` and `clientHandler` which enabled other extensions to use them. We didn't intend this behavior and don't want to expose any public API yet.
See:
> https://code.visualstudio.com/api/references/vscode-api#extensions
> Extension writers can provide APIs to other extensions by returning their API public surface from the `activate` call.
This PR removes the return value from `activate` and refactors the `workspaces.spec.ts` test, which used this API.

Remove public api

---

.eslintrc.json
package-lock.json
package.json
src/clientHandler.ts
src/commands/generateBugReport.ts
src/extension.ts
src/languageServerInstaller.ts
src/providers/moduleCalls.ts
src/serverPath.ts
src/showReferences.ts
src/telemetry.ts
src/test/integration/codeAction.test.ts
src/test/integration/completion.test.ts
src/types.ts
src/utils.ts
src/vscodeUtils.ts
tsconfig.json

This PR enables strict mode for TypeScript, resulting in a wide range of type checking behavior that guarantees program correctness.
I tried to do one commit per file, sometimes explaining my choices.

Use more strict TypeScript configuration

---

src/extension.ts
src/providers/moduleCalls.ts
src/providers/moduleProviders.ts
src/vscodeUtils.ts

This modifies the moduleCalls and moduleProviders views and the updateTerraformStatusBar function to detect if the open file is an `Untitled` file or other type of file and return early instead of trying to determine Terraform module information.
Previously the editor would attempt to determine terraform module status whenever a file was opened. This worked well if a Terraform file was opened, but would throw exceptions if a file was opened that did not contain Terraform code. This includes `Untitled` files which are open files that are not saved yet and don't exist on the filesystem yet. The fix is to ignore any non Terraform file.
This contains a naive check to determine if a file is a Terraform file, which checks the file extension for `tf`. This suits for now but possibly might need …

Fix Detecting Terraform files in status calls

---

.eslintignore
jest.config.js
src/test/helper.ts
src/test/unit/detector.test.ts
src/test/unit/updater.test.ts

This PR updates the `.eslintignore` to not exclude the `test/` directory. The change enables eslint to check the tests, too.

Enable eslint for tests

---

src/test/unit/detector.test.ts
src/test/unit/installer.test.ts
src/test/unit/updater.test.ts

The `mocked` helper function is deprecated and will be removed in `ts-jest` 28.0.0. It has been integrated into jest-mock package as a part of Jest 27.4.0.
Closes #885

use jest.mocked instead of ts-jest mocked

---

package.json

After recent changes there's an increased overhead of pre-calculating the number of references for the code lens.
We can therefore make this code lens opt-in to avoid the extra lookups which are likely causing the excessive CPU consumption as code lens get refresh upon editor focus and generally very often.
This should help address https://github.com/hashicorp/terraform-ls/issues/733

Make reference count code lens opt-in

---

.github/workflows/test.yml
package-lock.json
package.json
src/test/runTest.ts

Change default `npm test` behavior to use the version of VS Code specified in the `VSCODE_VER` environment variable, instead of testing hardcoded versions inside `runtest.ts`.
`VSCODE_VER` supports latest, insiders and version numbers lik 1.55.0.
If the `VSCODE_VER` environment variable is not specified, then the latest stable version of VS Code is automatically used.

Test VS Code Version Matrix

---

.vscodeignore

This ignores the jest config file when packaging the extension.

Ignore jest config when packaging

---

package.json

This adds a deprecation message to the `terraform.languageServer.requiredVersion` setting.
This setting will be removed in a future release when this extension adopts platform specific extension publishing.
In a future release, the extension will bundle the terraform-ls binary inside the published VSIX. This eliminates the need to download the binary at runtime, but also means the user cannot change the terraform-ls version used. Since they cannot change the version, this setting will no longer be needed.
Users who wish to use a different version than the one shipped with the extension will use `terraform.languageServer.pathToBinary` instead and install the terraform-ls binary using one of the release artifacts or through a package manager.
More detailed documentation on this process will …

Deprecate terraform.languageServer.requiredVersion

---

package-lock.json

This PR updates a couple dependencies to their latest version:
`vsce` to 2.6.4 which comes with the latest version of [markdown-it](https://github.com/advisories/GHSA-6vfc-qv3f-vr6c)
`mocha` to 9.2.0 which comes with the latest version of [nanoid](https://github.com/advisories/GHSA-qrpm-p2h7-hrv2)
`node-fetch` to 2.6.7 which patches [CVE-2022-0235](https://github.com/advisories/GHSA-r683-j2x4-v87g)

Update deps to fix Dependabots alerts

---

.github/workflows/preview.yml

Preview builds do not use git tags, so remove the GitHub Action filter checking for them.

Fix preview publish trigger

---

.github/workflows/preview.yml

This adds a workflow_dispatch event to the preview workflow so that we can publish the extension manually.

Manual Preview release workflow dispatch

---

.github/workflows/test.yml
.vscode/extensions.json
.vscode/settings.json
DEVELOPMENT.md
jest.config.js
package-lock.json
package.json
tests/snapshot/terraform/basic.tf
tests/snapshot/terraform/basic.tf.snap
tests/unit/terraform/basic.tf

This commit:
- Adds testing infrastructure using vscode-tmgrammar-test to test the Terraform tmGrammar file. A minimal example file is used to demonstrate basic testing. Additional tests will be added as grammar is modified or changed.
- Add tmGrammar schema to project to enable VS Code to provide intellisense and minimal validation of the tmGrammar files, whether they are json or yaml.
- Updates the DEVELOPMENT readme and adds documentation on how to edit and test the Terraform tmGrammar
- Automatically tests the grammar on every pull request

Terraform TextMate Test Infrastructure

---

syntaxes/terraform.tmGrammar.json
tests/snapshot/terraform/variables_input.tf.snap

This PR updates the syntax highlighting for the deprecated `list()` and `map()` functions.
Closes #610

Update list/map syntax highlighting

---

package.json
syntaxes/terraform.tmGrammar.json
tests/snapshot/terraform/basic.tf.snap
tests/snapshot/terraform/blocks.tf.snap
tests/snapshot/terraform/comments.tf.snap
tests/snapshot/terraform/data_sources.tf.snap
tests/snapshot/terraform/expressions_conditional.tf.snap
tests/snapshot/terraform/expressions_dynamic.tf.snap
tests/snapshot/terraform/expressions_for.tf.snap
tests/snapshot/terraform/expressions_functions.tf.snap
tests/snapshot/terraform/expressions_operators.tf.snap
tests/snapshot/terraform/expressions_splat.tf.snap
tests/snapshot/terraform/expressions_strings.tf.snap
tests/snapshot/terraform/modules.tf.snap
tests/snapshot/terraform/providers.tf.snap
tests/snapshot/terraform/variables_input.tf.snap
tests/snapshot/terraform/variables_local.tf.snap
tests/snapshot/terraform/variables_output.tf.snap
tests/unit/terraform/basic.tf

This commit changes the TextMate scopeName from `scope.terraform` to `source.terraform` inside the Terraform TextMate Grammar file.
The current scopeName for the Terraform TextMate grammar is `scope.terraform`: https://github.com/hashicorp/vscode-terraform/blob/59987ae480a970b5955c94260abfa41fccb8577e/syntaxes/terraform.tmGrammar.json#L2
According to the TextMate documentation, the scopename should follow this naming conventions:
> scopeName — this should be a unique name for the grammar, following the convention of being a dot-separated name where each new (left-most) part specializes the name. Normally it would be a two-part name where the first is either text or source and the second is the name of the language or document type.
This means we need to change the Terraform scope name to …

Move TextMate scope.terraform to source.terraform

---

.github/workflows/syntax.yml
.github/workflows/test.yml

This runs the syntax tests only if the grammar files change in the syntaxes directory.
As we start to modify the syntax and grammar more, we'll be running tests more frequently. We don't need to incur the cost or time of running the entire suite when we are testing grammar changes.

Run syntax tests when grammar changes

---

package.json

This fixes a bug with comment toggling found while I was using the extension. Basically, if a user opens a `*.tfvars` first, it breaks the comment toggling in `*.tfvars` files till the session is reloaded. This adds the explicit mapping to the configuration files, and activates the extension once a `*.tfvars` file is opened, and doesn't rely on a `*.tf` file to be loaded first.
Resolves #936 and may be related to #480

Resolve issue with tfvars comment toggling

---

language-configuration.json

This PR restores changes from 3ae5eea0b2689d2839db75b388d9baadd81d0f55 to detect region markers (`#region` and `#endregion`) used for [folding blocks of code](https://code.visualstudio.com/docs/editor/codebasics#_folding).
https://user-images.githubusercontent.com/1751980/153667692-0578a05e-5135-4602-8092-78a99a8d6297.mov

Restore region markers support

---

syntaxes/terraform.tmGrammar.json
tests/snapshot/terraform/basic.tf.snap
tests/snapshot/terraform/blocks.tf.snap
tests/snapshot/terraform/data_sources.tf.snap
tests/snapshot/terraform/expressions_dynamic.tf.snap
tests/snapshot/terraform/issue927.tf.snap
tests/snapshot/terraform/modules.tf.snap
tests/snapshot/terraform/providers.tf.snap
tests/snapshot/terraform/variables_input.tf.snap
tests/snapshot/terraform/variables_local.tf.snap
tests/snapshot/terraform/variables_output.tf.snap
tests/unit/terraform/basic.tf
tests/unit/terraform/resource.tf

This changes the existing block matcher to differentiate the type and name of a given block.
Previously the type and name of a block were scoped as `string.quoted.double`. This change scopes them to an `entity.name.tag`, which is commonly used to indicate a tag or attribute.
This will match Terraform blocks like `resource "aws_instance" "web" {` or `module "foo" {`
This will match Terraform blocks like `module "foo" {` or `variable`.
This will leave alone blocks without types or names:
> **Note:** The LS needs to be disabled for you to see this until the semantic tokens are updated in the terraform-ls project.
Fixes #710

Add new scope for block type and name 

---

syntaxes/terraform.tmGrammar.json
tests/snapshot/terraform/expressions_for.tf
tests/snapshot/terraform/expressions_for.tf.snap

This PR adds support for nested expressions.
Since all regular expressions used in grammar match rules must apply to a single line at a time, we can't reuse the existing `for` patterns. So instead, new patterns are added to the brackets and objects patterns to match `for` and `if` statements.
Before
After
Closes #926

Fix highlighting for nested expression syntax

---

.github/workflows/test.yml

This fixes the Markdown file glob for the GitHub Test Action.

Fix ignore markdown files

---

package.json

This PR updates the settings description for `terraformLogFilePath` to reflect the latest findings.
Related to https://github.com/hashicorp/terraform-ls/pull/807

Update description for log file argument

---

.github/workflows/test.yml

As other people have reported in https://github.com/actions/virtual-environments/issues/4856 there are some issues with windows-2022 (which we consume through `windows-latest`) causing our windows builds to occasionally time out through no fault of our own.
This is in order to address that temporarily but I am hoping we can use 2022 soon, once the bugs are fixed by GitHub.

github: pin Windows to 2019 to prevent timeouts

---

.gitattributes
.vscode/settings.json

This is to help in editing in VSCode (where it automatically picks `JSON with Comments` instead of `JSON`) and also in highlighting in GitHub UI, so comments are no longer treated as "invalid" and no longer highlighted as red.
See https://code.visualstudio.com/docs/languages/identifiers and https://github.com/github/linguist/blob/master/docs/overrides.md#using-gitattributes

Ensure VSCode JSON files are treated as JSON with comments

---

package.json

Specify the workspace execution location so that VS Code prefers to install this extension in the remote host when using Remote Extensions like the Remote Container, SSH, or WSL extensions. VS Code will still install this extension locally when working on the local machine.
For more inforamtion see:
- https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location
- https://code.visualstudio.com/api/advanced-topics/extension-host#preferred-extension-location
Install to local:
Install to WSL:

Advertise proper exectution location

---

package.json
src/test/integration/workspaces.test.ts

In terms of Changelog entries I expect we can basically link to https://github.com/hashicorp/terraform-ls/releases/tag/v0.26.0

bump LS to 0.26.0

---

package.json

This setting is not used by the extension.

Deprecate maxNumberOfProblems

---

.github/workflows/test.yml
.prettierignore

This adds a Github Action to check if there are any formatting changes to any PR submitted and ignores the package.json file when running prettier.
This is to prevent churn when adding new options to the package.json manifest.

Format semantic token settings

---

package.json

This was deprecated in https://github.com/hashicorp/vscode-terraform/commit/3668713bd926678d7393afc5d50659033b524e88 and the usage was removed in https://github.com/hashicorp/vscode-terraform/commit/2a3888160b4b9aa7165f0eceb07cc5e8986b1f2e. This no longer needs to be in the extension.

Remove terraform.languageServer.requiredVersion

---

package.json

This groups and orders the existing settings into VS Code Setting sections while preserving the exact keys for each setting.
The extension previously utilized different prefixes to indicate different areas like terraform-ls.rootModules or terraform-ls.terraformExecTimeout. This leaves settings in a seemingly random order in the Settings UI and makes it hard to autocomplete inside the json file.
We solve this by organizing the extension settings into sections in the `contribute` part of the package.json manifest. These sections provide a logical order to extension settings, especially if the extension has many settings or many settings that are nested.
This also allows us to separate out configuration options, like a separate section for Experimental Options:

Organize extension settings into Sections

---

src/extension.ts

This PR prevents the preview extension from activating when the stable extension is enabled, or vice versa.
To test:
> Note: You cannot test this inside the Extension host.
- Package hashicorp.terraform
- Package hashicorp.terraform-preview
- Install both in a new VS Code Install (or ensure your ~/.vscode/extensions directory does not have any existing installs)
On installing the second VSIX, you should get an error message popup. Disabling one and reloading should show a properly activated extension. Enabling the other one and disabling the first should produce a error message pop up.

Prevent preview from activating when stable is enabled

---

package.json
src/clientHandler.ts

Adds the terraform-ls setting that controls whether warnings are shown when editing single Terraform files.
Works with https://github.com/hashicorp/terraform-ls/pull/843

Add terraform.languageServer.ignoreSingleFileWarning setting

---

build/preview

While testing #1032, I noticed that the test for the `LANGUAGE_SERVER_VERSION` variable isn't working if the variable is unset, and the script exits with an error. This PR fixes the test.
```bash
$ ./build/preview
./build/preview: line 12: LANGUAGE_SERVER_VERSION: unbound variable
```

Fix LANGUAGE_SERVER_VERSION test in preview script

---

build/downloader.ts
package.json

https://github.com/hashicorp/terraform-ls/releases/tag/v0.27.0
I also adjusted the log message.
I initially ran `rm bin/terraform-ls` and then was left confused why am I getting `terraform-ls path exists` when it's already gone. Only after reading the relevant code more carefully I realized that we're checking for the parent directory.
We could be checking the binary path instead of the parent dir, but I thought this just improves the UX without changing the behaviour.

deps: bump LS to 0.27.0

---

package.json

This setting is not used by the extension.

Remove `terraform.languageServer.maxNumberOfProblems`

---

package.json
src/providers/moduleProviders.ts

This adds the refresh button to the Terraform Module Providers view and hooks it up to the refresh method.

Add Module Providers view refresh button

---

.github/dependabot.yml

The motivation is to reduce the noise coming mainly from frequently updated `@types/*` packages which are not critical for us, along with most dev dependencies.
`@hashicorp/js-releases` is one we maintain ourselves and don't release as frequently, so that shouldn't present the same challenge as the others.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval

dependabot: Reduce interval for dev dependencies to weekly

---

package-lock.json
package.json
src/clientHandler.ts
src/extension.ts
src/providers/moduleCalls.ts
src/providers/moduleProviders.ts

This removes generating a command prefix when registering commands for the language client connecting to terraform-ls.
Previously the extension would create a LanguageClient/terraform-ls pair per 'folder' in a workspace. This means there was a terraform-ls process per folder to keep track of. The https://github.com/hashicorp/terraform-ls/pull/502 PR enabled a single terraform-ls process to handle multi-folder workspaces, which meant we could refactor the extension In https://github.com/hashicorp/vscode-terraform/pull/845 to use a single LanguageClient instance. A leftover from the original design was a prefix for commands registered between terraform-ls and the client. This ensured unique command IDs when multiple clients were present, but is no longer necessary with a single language …

Remove command prefix

---

src/extension.ts

This extracts functions, re-orders execution and otherwise cleans up the main entry point for the extension.
Migrating settings is extracted to a function to prepare for the work to be done renaming settings later on.
The command registration calls are reorganized to prioritize registering first those that do not require the terraform-ls to function. Starting the terraform-ls binary is then called directly before registering the rest of the commands and providers.
The end result is registering and activating the parts that need the LS only if it is enabled.

Optimize main entry point execution path

---

src/clientHandler.ts
src/extension.ts
src/providers/moduleCalls.ts
src/providers/moduleProviders.ts
src/utils/clientHelpers.ts
src/utils/serverPath.ts

This extracts the LanguageClient creation from ClientHandler and puts it directly inside the activation point.
In order to implement https://github.com/hashicorp/terraform-ls/issues/722 we need to add a new StaticFeature to register a client-side command for terraform-ls to call when it knows the `terraform.providers` view needs to be refreshed.
StaticFeatures are registered using the LanguageClient.registerFeature method, which means the ClientHandler class needs to create the StaticFeature. The StaticFeature needs both the LanguageClient and `terraform.providers` view created before it can be initialized. The LanguageClient is created by the ClientHandler class. This all results in a cyclic dependency.
We could resolve this cyclic dependency by adding more responsibility to …

Extract LanguageClient from ClientHandler

---

CHANGELOG.md
src/extension.ts
src/features/moduleProviders.ts
src/features/types.ts
src/providers/moduleProviders.ts

This introduces a StaticFeature which registers a handler for the `client.refreshModuleProviders` request which terraform-ls can call to refresh the data shown in the Terraform Providers view. The terraform-ls server was modified to send `client.refreshModuleProviders` requests in https://github.com/hashicorp/terraform-ls/pull/902

Automatically refresh Terraform Providers View when providers change in open document

---

src/extension.ts
src/features/moduleCalls.ts
src/features/moduleProviders.ts
src/features/types.ts

This commit automatically refreshes the Terraform Module Calls View when providers change in open document.
This introduces a StaticFeature which registers a handler for the `client.refreshModuleCalls` request which terraform-ls can call to refresh the data shown in the Terraform Module Calls view. The terraform-ls server was modified to send `client.refreshModuleCalls` requests in https://github.com/hashicorp/terraform-ls/pull/909

Automatically refresh Terraform Module Calls View

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

This proposes two changes:
1. Removes the tickboxes - it doesn't seem to bring much value as anecdotally many people just leave it out
2. LS is now bundled with the extension, so we no longer need to ask for the version as it's implied from extension version.

github: Update issue templates

---

CHANGELOG.md
package.json

Closes https://github.com/hashicorp/vscode-terraform/issues/1040

Bump syntax 0.3.0

---

src/extension.ts

Requires https://github.com/hashicorp/terraform-ls/issues/15 (LS `0.28.0+`)
Closes https://github.com/hashicorp/vscode-terraform/issues/1068

Watch `**/*.tf` & `**/*.tfvars` by default

---

.prettierignore

This removes package.json and syntaxes from the .prettierignore file.
We previously wanted package.json to not be formatted because of the addition of the semantic token data, but keeping it formatted is more important that the extra lines that adds.

Remove package.json from .prettierignore

---

package.json

This sets the following settings to `machine-overridable` scope. This ensures these settings will be read in the correct location whether the user is using the extension locally or in a remote context like the Remote Extensions or Codespaces.
It is set to `machine-overridable` instead of just `machine`, to still allow users to have these settings set inside a Workspace file or in the Workspace folder. If we set it to just `machine`, the settings would not be modifiable in the Workspace file or in the Workspace folder scopes.
```
terraform.languageServer.path
terraform.languageServer.args
terraform.languageServer.terraform.path
terraform.languageServer.terraform.timeout
terraform.languageServer.terraform.logFilePath
terraform.languageServer.rootModules …
```

Set proper scope for machine based settings

---

package.json
src/extension.ts

Create a new Terraform [View Container](https://code.visualstudio.com/api/ux-guidelines/views#view-containers) that will house the existing `terraform.providers` and `terraform.modules` views. These views will no longer be inside the Explorer View Container.
This Terraform View Container will support all the built-in mechanisms users expect out of views, most notable of which is the ability to move it to other places in the editor like the new SideBar:
Or be able to be hidden altogether:
This enables us to have a single place to land new views as well as allow the user to customize as they see fit.

Terraform View container

---

.github/workflows/test.yml
README.md
package-lock.json
package.json

This raises the minimum supported VS Code version from 1.61.1 to 1.65.2

Bump vscode from 1.61.1 to 1.65.2

---

package.json
src/extension.ts
src/utils/clientHelpers.ts

Add TCP connection settings
This commit adds `terraform.experimentalFeatures.languageServer.tcp.port` to enable connecting to a terraform-ls instance using TCP instead of STDIO. The terraform-ls instance has to be already running, this will not start it for the user.
This also adds a custom error handler to the LanguageClient implementation. This custom implementation attempts to start the LS and returns after one failure, but ensures an error window is raised when it fails to start or connect to a terraform-ls instance. This is needed because the LanguageClient handles errors by default but relies on the OutputChannel not being hidden to show errors.

TCP Client Handler

---

package.json

This adds a when clause to only offer to enable the language server if it's disabled, or to disable if it's enabled. It also only shows commands that require the language server if the language server is enabled.
Enabled:
Disabled:

Scope languageServer enablement commands

---

docs/settings-migration.md
package.json
src/extension.ts

This scopes all path related and dependent settings to machine scope. This restricts the settings to only be specified in the User or Remote settings, not workspace or folder settings.
This allows a setting to have different values depending on where VS Code is being run in. For example, if a user runs this extension in Windows locally and in an Ubuntu WSL instance they need to specify two different paths to terraform-ls (if they use a custom install location). They configure a Windows path in their User settings and configure a Linux path in their Remote WSL session. The correct path will be resolved in either session.

Set machine scope to path settings

---

src/commands/terraform.ts
src/commands/terraformls.ts
src/extension.ts
src/features/moduleCalls.ts
src/features/moduleProviders.ts
src/features/showReferences.ts
src/features/telemetry.ts
src/handlers/errorHandler.ts
src/settings.ts
src/utils/clientHelpers.ts

- Centralize and standardize command registration and enablement
- Centralize and standardize feature registration and enablement
- Extract functionality to dedicated files
- Eliminate cyclic imports
- Dispose disposables properly
- Extract settings.ts
This moves all setting related functions to a new file called settings.ts. This is in preparation for a more formal settings infrastructure.
- Remove enabled function
This prefers direct detection of the setting rather than the function. This is in preparation for a more formal settings management in the future.
- Extract Terraform command registration
This extracts registering Terraform commands to a central class. This cleans up extension.ts from having lots of registrations, enables a central place to keep track of terraform-ls execution …

Refactor main entry point

---

src/features/showReferences.ts

The language server will enable reference count code lens when it receives the `experimental.showReferencesCommandId`, which we seem to send always, i.e. we always enable it. Consequently we (correctly) don't register the command, so upon clicking to the code lens, it errors out:
This makes it so that the client only sends that command ID when the feature is actually enabled.

fix: avoid sending command ID when codelens is disabled

---

README.md
src/extension.ts
src/utils/vscode.ts

This adds logic to handle UNC WSL Paths that will not work in terraform-ls. It prompts the user to switch to the Remote WSL extension or allows the user to ignore the prompt.
Needs https://github.com/hashicorp/terraform-ls/pull/1057 to fully function

Handle Invalid WSL Uri

---

CHANGELOG.md
src/extension.ts
src/handlers/errorHandler.ts
src/utils/vscode.ts

This removes the duplicate exception telemetry from ExtensionErrorHandler as the LanguageClient start exception handler already sends a exception telemetry event.

handle exception reporting

---

src/extension.ts

This commit ensures all commands that control terraform-ls are registered regardles of whether or not terraform-ls is enabled. This allows the when clauses to work appropriately but still have the commands registered.

Fix enable terraform-ls after disbaling

---

.github/workflows/test.yml

To make sure we're doing a clean install of the dependencies and pick any inconsistencies between the `package.json` and lockfile.

Use `npm ci` for installing dependencies inside CI

---

.github/workflows/publish.yml

This is a succession to https://github.com/hashicorp/vscode-terraform/pull/388, which adapts publishing to OpenVSX embedded in the publishing workflow in GitHub Actions.
Fixes #379 
Before using this it is necessary to set up an `OVSX_PAT` GitHub Action secret with the value from [open-vsx.org/user-settings/tokens](https://open-vsx.org/user-settings/tokens). A claim of the `hashicorp` namespace will be also required (this can be done by submitting [an issue](https://github.com/EclipseFdn/open-vsx.org/issues/new?assignees=&labels=namespace&template=claim-namespace-ownership.md&title=Claiming+namespace+%5Bname%5D) in the OpenVSX repo).

Add OpenVSX publishing

---

.github/workflows/preview.yml
.github/workflows/publish.yml

This PR updates the publishing workflows and replaces the deprecated `set-output` command:
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/Show less
In the preview workflow the extension version wasn't used, so I've removed the read.

Update `set-output` in CI workflow

---

.github/workflows/test.yml

[The issue](https://github.com/hashicorp/vscode-terraform/pull/968), why we pinned the windows version to 2019 should be resolve by now. Let's bump this to latest.

ci: Bump `windows-2019` to `windows-latest`

---

package.json

This is to bring in https://github.com/hashicorp/syntax/pull/49

deps: bump syntax to 0.4.1

---

.github/workflows/issue-comment-created.yml
.github/workflows/lock.yml
.github/workflows/preview.yml
.github/workflows/publish.yml
.github/workflows/stale.yml
.github/workflows/test.yml

The intention here is to reduce the security risk posed by the supply chain - i.e. externally maintained GitHub Actions.
The expectation is that dependabot will continue to update these hashes as and when new versions become available.

github: Pin external GitHub Actions to hashes

---

.github/workflows/publish.yml

Unsure why this wasn't caught within the PR - I guess GitHub doesn't validate the workflow files automatically until they're in `main` 🤷🏻 (except of course for the ones which run as part of the PR submission)
https://github.com/hashicorp/vscode-terraform/actions/runs/3713995911

ci: fix typo in publish workflow

---

.github/CODEOWNERS

As per our internal discussions, this helps differentiate between engineers on the team who need to be pinged about reviews and anyone else who does not.

github: Update CODEOWNERS file

---

.github/workflows/stale.yml

This PR proposes a few changes to the `stale` GHA workflow, which was effectively unused due to one of the settings set more conservatively.
Specifically, we set `days-before-stale: '-1'` which means that the bot would never attempt to mark issues as stale by itself. That first step was left to us, but I think nobody even realised this is the case and so nobody ever assigned `stale` label to an issue/PR.
With some older issues being accumulated in the repo, I wanted to update the settings, such that we can more proactively tackle the backlog and communicate expectations to the contributors/reporters.
- all automation remains scoped to just issues labelled `waiting-response`
- bot will automatically label an issue/PR as `stale` after 30 days of no response and comment with an updated …

github: Adjust settings of the stale workflow

---

package.json

Ensure webpack watch uses development mode to prevent webpack from detecting changes inside node_modules and endlessly building.

Fix endless webpack build on windows

---

.vscode/extensions.json
DEVELOPMENT.md

We now need problem matchers specific to Webpack instead of esbuild.

Update recommended problem matchers

---

src/extension.ts
src/features/terraformVersion.ts
src/features/types.ts
src/terraform.ts

This uses a StaticFeature to provide a LanguageStatusItem that displays the version of terraform that terraform-ls knows about.

Terraform Version LanguageStatusItem

---

.github/workflows/test.yml
README.md
package-lock.json
package.json

This raises the minimum required VS Code version from `1.67.2` to `1.75.1`.
About 90% our users are using `>= 1.75`

Bump VS Code from `1.67.2` to `1.75.1`

---

package-lock.json
package.json
src/extension.ts
src/providers/authenticationProvider.ts
src/providers/tfc.ts

This implements the `vscode.AuthenticationProvider` interface and creates a TFC specific provider. This handles listing existing sessions, creating and removing sessions.
Storing sessions/tokens will be improved by https://github.com/hashicorp/vscode-terraform/issues/1397. Currently it only securely stores the token. Future improvement can be done to prevent looking up user data every time the session is reloaded.
The TFC instance to target is defaulted to `app.terraform.io` with a configuration setting to override. This was added in https://github.com/hashicorp/vscode-terraform/issues/1398. Future work should discover whether detecting the TFC instance from the configuration available in the current working space is desirable.
One of the primary ways a user will trigger authentication …

Implement Terraform Cloud Authentication Provider

---

package.json

Beginning with VS Code 1.74.0, languages and commands contributed by the extension do not require a corresponding onLanguage or onCommand activation event declaration for the extension to be activated.

Remove default activation events

---

src/providers/authenticationProvider.ts

Depends on https://github.com/hashicorp/vscode-terraform/issues/1397
(can be repointed to `f-tfc` once that PR is merged)
--- 
I know most of the existing logic was copied from https://github.com/microsoft/vscode-extension-samples/blob/main/authenticationprovider-sample/src/authProvider.ts and so these notes/questions apply to that implementation too.
I may be wrong but according to my understanding we should not need all that event listening logic.
I don't know where exactly the data in `SecretStorage` is actually stored (disk, OS keychain, ...?) but I could imagine that the data there may somehow get removed without the sessions getting removed, which would then leave us in inconsistent state? Aside from such seemingly rare scenario I do not see the use case for …

Store all session data in `vscode.SecretStorage`

---

src/extension.ts
src/providers/authenticationProvider.ts

This adds a new prompt when the login workflow is initiated that asks the user how they want to authenticate: from the terraform cli config file, generate a new token on the web, or enter it manually.
The user can choose to have the extension read the terraform cli configuration file for the token. This means the user can reuse tokens they already configured to use with TFC without having to copy paste or create new tokens.
This also adds a user prompt to open the TFC website to generate a user token. This reuses the terraform cli login page to prompt the user to generate a new token.
If the user selects to enter an existing token, a new prompt is opened where the user can enter the token.
https://github.com/hashicorp/vscode-terraform/assets/272569/39c5103f-3d3f-440e-a61f-9f2c0439b9d1

TFC Login command

---

src/providers/tfc/workspaceProvider.ts

This commit refreshes the runs view when refreshing the workspace view by adding a call to the runDataProvider.refresh when performing workspaceProvider.refresh.
If a user has selected a workspace, then refreshes the view, the selected workspace tree item is passed to the runDataProvider so that the runs for that workspace are refreshed.
If no workspace is selected, then the runDataProvider is passed undefined, which will clear it's view. The user can then select a workspace to view runs.

Refresh runs when refreshing workspaces

---

.github/workflows/add-copyright-headers.yml
.github/workflows/test.yml

This is a solution we've been trialing on the CDK team and it's working well for us so I figured I'd propose it to this team as well.
Rather than failing a check on PRs if the copyright headers are missing (which is potentially annoying to community contributors who then either have to manually copy-paste the headers or install HashiCorp's copywrite tool), this adds a new commit on any PRs that are missing the headers that adds them in automagically. (If no headers are missing then it does nothing.)

Add copyright headers automagically instead of failing a check on PRs

---

package.json
src/providers/tfc/workspaceFilters.ts
src/providers/tfc/workspaceProvider.ts
src/terraformCloud/project.ts

Implements parts of #1452
---
This PR adds filtering of workspaces by project.

Implement workspace filtering by project

---

package.json
src/providers/tfc/workspaceProvider.ts

This commit adds a command and button to the Workspace View to open the selected workspace in the system browser

Add open workspace in browser command

---

src/extension.ts
src/features/terraformCloud.ts
src/providers/authenticationProvider.ts
src/terraformCloud/index.ts

This adjusts the silent login workflow to call the organization picker at the correct times.
A user can login either using our command palatte command or by clicking the User Account icon and selecting our provider (called a silent login flow by the docs). This silent flow creates the session but does not call our organization picker. The organization picker needs to call out to TFC to get a list of organizations to choose from, which requires authentication to TFC. Authentication to TFC requires the apiClient to have a token, which it asks using getSession.
We can't add the organization picker in createSession because it would call getSession before createSession finishes, leaving no session for getSession to find. This creates a chicken-and-the-egg scenario. To add further complication, …

Fix silent login workflow

---

src/providers/tfc/helpers.ts
src/providers/tfc/runProvider.ts
src/providers/tfc/workspaceProvider.ts
src/terraformCloud/filter.ts
src/terraformCloud/run.ts
src/terraformCloud/workspace.ts

This improves the detail shown when hovering over a Workspace Tree item in the Workspace view. This detail includes number o resources, terraform version, last updated date, VCS url, execution mode and auto apply state.
This also adds a status icon to the item, so that the status of the last run shows as the status of the workspace, just like the TFC website.
More information about the last run status could have been added to the hover, but this makes the hover box large enough it can be clipped when the editor zoom is large. This information is already shown in the Run view, so is not absolutely needed here. If that information is useful, it can be added to the item by adding child nodes.

Workspace View Detail

---

package-lock.json
package.json
src/providers/tfc/runProvider.ts
src/providers/tfc/workspaceProvider.ts
src/terraformCloud/run.ts
src/terraformCloud/workspace.ts

This is to reflect the patch upstream https://github.com/ecyrbe/zodios/pull/471
I ran the schemas through all the data we have available in our shared org and they all comply.

bump zodios to `v10.9.2` and update incorrect API schemas

---

src/extension.ts
src/features/terraformCloud.ts
src/providers/authenticationProvider.ts
src/providers/tfc/runProvider.ts
src/providers/tfc/workspaceProvider.ts

This PR uses the built-in telemetry feature to collect anonymous TFC usage information.
We track
* **Auth related**
* Login
* With existing token
* With stored token
* With opening the browser  
* Login success
* Login fail
* Logout
* **Organization related**
* Open organization picker
* Select Create Organization
* Select Refresh Organization
* **Workspaces related**
* Refresh
* Filter
* Open in browser
* Successful fetch 
* **Runs related**
* Refresh
* Open in browser
* Successful fetch

Add telemetry for TFC integration

---

src/providers/authenticationProvider.ts
src/providers/tfc/organizationPicker.ts
src/providers/tfc/runProvider.ts
src/providers/tfc/workspaceProvider.ts
src/terraformCloud/index.ts
src/test/integration/mocks/server.ts

This creates an exported constant for the Terraform Cloud Web URL and replaces all hardcoded references.

Standardize TFC URL Location

---

package-lock.json
package.json
src/features/terraformCloud.ts
src/providers/tfc/contentProvider.ts
src/providers/tfc/helpers.ts
src/providers/tfc/runProvider.ts
src/providers/tfc/workspaceProvider.ts
src/terraformCloud/apply.ts
src/terraformCloud/index.ts
src/terraformCloud/plan.ts
src/terraformCloud/run.ts

This PR adds the plan and apply log for runs. It also fixes some minor bugs and adds some QoL improvements (see commits).

Plan Apply Log

---

package.json
src/providers/tfc/workspaceProvider.ts

This fixes two problems.
Previously, if the org picker was never shown, the `terraform.cloud.organizationsExist` key would be missing from the context, resulting in empty workspaces view:
Setting the key from within the workspace view based on some logical assumptions brings back the expected welcome view:
Secondly if the user picks an org which they have still pending invitation for, we'd just display no workspaces with no more context (as above). Now we check for memberships and show a separate new welcome view in such a case:

TFC: Fix missing context key & account for pending org invitations

---

package.json

This is to complement https://github.com/hashicorp/vscode-terraform/pull/1502 (which targets `f-tfc` branch)
It brings in the following enhancements: https://github.com/hashicorp/terraform-ls/releases/tag/v0.31.3
We can update the changelog in `main` as we get closer to a stable release.

bump LS version to 0.31.3

---

package.json

This is to bring the following enhancements: https://github.com/hashicorp/terraform-ls/releases/tag/v0.31.3
I raised https://github.com/hashicorp/vscode-terraform/pull/1503 with the same change to target `main` and we can update https://github.com/hashicorp/vscode-terraform/pull/1501 once this is merged to reflect the changes.

TFC: bump LS version to 0.31.3

---

README.md

Copy pasted this snippet into .vscode/settings.json and it wasn't a valid json due to a missing comma, adding that.

Correct invalid json in README.md

---

src/extension.ts
src/features/languageStatus.ts
src/features/terraformVersion.ts
src/status/installedVersion.ts
src/status/language.ts
src/status/requiredVersion.ts

This sets a busy status when finding out the terraform version, which approximates a loading status for the extension because the request for status happens after all the other requests happen "in the background". So, we get a loading bar for the extension in the lower right hand corner.
https://github.com/hashicorp/vscode-terraform/assets/272569/e3472dd4-97d1-43c1-9124-d1bd173ab7c0

Language Status indicator

---

src/extension.ts

In general VS Code is supposed to allow multiple extensions to provide diagnositics for a file without collision. There are [reported cases](https://github.com/sourcery-ai/sourcery-vscode/issues/121) where multiple extensions that claim support for the same language overwrite diagnositics. To avoid this, we can set diagnosticCollectionName explicitly and create our own collection.
While we haven't specifically seen this happen for us, it may have happened and we are not the only ones to set it explicitly.
Reference: https://github.com/microsoft/vscode-languageserver-node/blob/f2ff7d55464a1f58f978cb6635bd8865f050553c/client/src/common/client.ts#L1080-L1084

Explicitly set diagnosticCollectionName

---

package.json
src/providers/authenticationProvider.ts
src/providers/tfc/contentProvider.ts
src/providers/tfc/organizationPicker.ts
src/providers/tfc/workspaceFilters.ts

- Choose Sentence case for most phrases
- Always properly capitalize HashiCorp, Terraform, Terraform Cloud, and other HashiCorp products
- Prefer using just 'Terraform Cloud' instead of 'HashiCorp Terraform Cloud'
- Do not capitalize TFC concepts like workspace or organization unless its the start of a phrase
- Do not put periods at the end of phrases in buttons, welcome views, messages
- Do not use colons or semi colons before buttons in welcome views
Exceptions:
- VS Code always capitalizes view titles

Standardize text casing in TFC views

---

src/test/integration/codeAction.test.ts

The test for code actions can take slightlty longer to activate terraform-ls than the method open() accounts for. This adds a sleep to ensure that it's activated before we attempt to ask for supported code actions.

Add sleep to code action test

---

.github/workflows/test.yml
src/test/integration/completion.test.ts

This PR bumps the Terraform version used in the tests from `1.1` to `1.5`. This is more inline with our development environments.

Bump Terraform version in CI

---

package-lock.json

This also updates a transitive dependency `openpgp` to `5.10.1`, which should in turn address https://github.com/advisories/GHSA-ch3c-v47x-4pgp
While this was flagged as security alert my understanding is that it doesn't impact us (or our users) in any way, because `js-releases` does not use `readCleartextMessage` nor `verifyCleartextMessage` as per https://github.com/hashicorp/js-releases/blob/6b64ff2a17be14820d7cdef5fad8d45645e83a80/src/index.ts#L215-L231

deps: Bump js-releases to 1.7.0

---

package.json
src/settings.ts

Adds `terraform.validation.enableEnhancedValidation` setting to the initializationOptions sent to terraform-ls.
I chose to use `terraform.validation` as we expect to add future settings for this feature.
This relies on functionality to be added to terraform-ls to parse the new setting.

Introduce a new setting for enhanced validation

---

package-lock.json
package.json

This should only be merged when LS 0.32.0 is actually released, at which point the tests can re-run and should be green.

Prepare for 2.28.0 release

---

CHANGELOG.md
package-lock.json
package.json

Depends on
- https://github.com/hashicorp/terraform-ls/pull/1449
Fixes
- https://github.com/hashicorp/vscode-terraform/issues/1573
- https://github.com/hashicorp/vscode-terraform/issues/1574
- https://github.com/hashicorp/vscode-terraform/issues/1575
- https://github.com/hashicorp/vscode-terraform/issues/1576
- https://github.com/hashicorp/vscode-terraform/issues/1577

Prepare for 2.28.1 release

---

package.json
src/providers/tfc/runProvider.ts

With the introduction of TFCRunTreeItem, any method that operates on a specific type of treeitem must check it's type. This is especially important in order to only resolve the tooltip for the RunTreeItem and not for Plan or Apply treeitems.
This also makes the Plan and Apply buttons use the same codeicon.

Fix plan and apply item tooltip

---

package.json
src/features/terraformCloud.ts
src/providers/tfc/runProvider.ts
src/providers/tfc/workspaceProvider.ts

This PR adds a simple pagination to the workspaces view. We load the next page and append it to the tree view when a user clicks "load more".
Hitting refresh or using the project filter will reset the cache.
I'd like to improve the UX here, but it's not possible to programatically update the scroll position or deselect an item. Also, the current solution is cumbersome for 500+ workspaces, where a user would have to hit "load more" at least 10 times to get to workspaces further down the list. A filter (e.g. by name) might improve this in the future.

Add TFC workspace pagination

---

package-lock.json
package.json

Result of `npm i @hashicorp/js-releases`
This should also hopefully update the version constraints on `@babel/traverse` and allow us to bump it and get rid of the security scanner noise.

deps: bump js-releases to 1.7.1

---

package-lock.json

This PR bumps  `@babel/traverse`, `get-func-name`, and `semver` to address some security vulnerabilities.
```
❯ npm audit
@babel/traverse  <7.23.2
Severity: critical
Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code - https://github.com/advisories/GHSA-67hx-6x53-jw92
fix available via `npm audit fix`
get-func-name  <2.0.1
Severity: high
Chaijs/get-func-name vulnerable to ReDoS - https://github.com/advisories/GHSA-4q6p-r6v2-jvc5
fix available via `npm audit fix`
semver  <5.7.2 || >=6.0.0 <6.3.1
Severity: moderate
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
```

Bump `@babel/traverse`, `get-func-name`, `semver`

---

package.json
src/features/terraformCloud.ts
src/providers/tfc/applyProvider.ts
src/providers/tfc/logHelpers.ts
src/providers/tfc/planProvider.ts
src/providers/tfc/runProvider.ts
src/terraformCloud/apply.ts
src/terraformCloud/log.ts

Closes https://github.com/hashicorp/vscode-terraform/issues/1637
Follow-up:
- https://github.com/hashicorp/vscode-terraform/issues/1650
- https://github.com/hashicorp/vscode-terraform/issues/1651
--- 
Single panel
Both panels
https://github.com/hashicorp/vscode-terraform/assets/287584/dba715b2-1e95-4f40-b22b-cec4cdc76f57
While it may look simple and not as helpful without all the deeply structured data in the form of attributes etc. I'm afraid this is as much as we can squeeze out of the _structured logs_ without downloading the whole plan file and rendering all the things with the full knowledge of types etc. This would be a whole different story in terms of complexity though.
I found a few bugs which affected the existing plan log, so while implementing apply log correctly I also fixed …

TFC: Implement apply panel for structured output

---

.github/workflows/deploy.yml
CHANGELOG.md
DEVELOPMENT.md
build/downloader.ts

Based on https://github.com/microsoft/vscode-vsce/pull/908 and https://github.com/microsoft/vscode/pull/195559, it appears that extensions should no longer be published for the now removed `win32-ia32` target.

Remove `win32-ia32` build target

---

.github/workflows/test.yml
.vscode/tasks.json
src/test/runTest.ts

This removes executing terraform before the tests. As the terraform-ls progressed, it has moved away from requiring a terraform init run before being able to parse the configuration.

Remove terraform init from integration tests

---

.github/workflows/test.yml
.vscode/settings.json
src/test/integration/codeAction.test.ts

We removed calling `terraform init` for integration tests in https://github.com/hashicorp/vscode-terraform/pull/1645 and also removed the Terraform installation altogether. It turns out that the formatting code action still requires Terraform. 
This PR adds the installation of Terraform 1.6 to fix the testing issues on Windows and MacOS (the Ubuntu runner ships with Terraform installed).
VS Code automatically updates the workspace settings when the project is opened, so I've included that small change here as well.

Fix test failures on main

---

package.json

This renames the existing token type TokenTypeCapsule to TokenTypeComplex to aid readability and reflect existing naming conventions.
This token represents `list` in `type = list(string)` and similar, i.e. the name of the complex type. The term "capsule" has slightly different meaning in cty and HCL and we should not use it in this context.
Relies on https://github.com/hashicorp/terraform-ls/pull/1529

Rename TokenTypeCapsule to TokenTypeComplex

---

.github/workflows/test.yml
README.md
package-lock.json
package.json

As discussed yesterday, this PR bumps our minimal required VS Code version to 1.82.3. This completes the transition to Node.js 18.

Bump minimal engine version to `1.82.3`

---

.github/workflows/deploy.yml

This _partially_ reverts https://github.com/hashicorp/vscode-terraform/pull/1661 as a way of preventing any effects of a known upstream issue with the new version as discussed in https://github.com/actions/download-artifact/issues/249

github: Revert upgrade of artifact actions

---

package.json
src/features/terraformCloud.ts

- Hide Terraform Cloud commands
- Use proper titles for Terraform commands
Before:
After:
With TFC disabled:
With TFC enabled and not logged in:
With TFC enabled and logged in:

Configure command enablement

---

package.json

This removes `contributes.authentication` from the package.json manifest to restore workspace extension enablement.
From the [discussion thread](https://github.com/microsoft/vscode-discussions/discussions/930) and our investigation we can conclude (if not verify completely as there is no documentation) that `contributes.authentication` is a way to advertise use of the provider to outside extensions and not necessary for internal functionality. This means we can remove advertising the auth provider without breaking existing functionality.

Remove registering authentication provider

---

.github/CONTRIBUTING.md

This PR adds a similar file as we have for [terraform-ls](https://github.com/hashicorp/terraform-ls/blob/main/.github/CONTRIBUTING.md#releasing) to document the release process.

Add CONTRIBUTING file

---

package.json
src/commands/terraformls.ts
src/features/moduleCalls.ts
src/features/moduleProviders.ts
src/providers/moduleCalls.ts
src/providers/moduleProviders.ts
src/terraform.ts

This commit improves the welcome views for moduleProviders and moduleCalls by adding context variables to the views. This allows us to show different messages depending on the state of the open file inside the tree views.

Improve moduleProviders and moduleCalls welcome views

---

.eslintignore
.gitignore
.prettierignore
.vscodeignore
package-lock.json
package.json
src/terraformCloud/organization.ts
test/package-lock.json
test/package.json
test/specs/extension.ts
test/specs/language/terraform.ts
test/specs/views/terraform.ts
test/specs/views/tfc.ts
test/tsconfig.json
test/wdio.conf.ts
tsconfig.json

Introduces new tests using webdriver.io as an integration testing framework for vscode extensions.
This aims to supplement, not replace the existing testing inside terraform-ls. There are some things that are difficult to test with the current testing framework, such as the UI, and the interaction between the extension and the language server.
This is a first step towards a more comprehensive testing strategy for the extension. As such, it is not expected to be perfect, and will likely need to be iterated on. Also, we likely will move the location, but want to get the initial setup in place.

Webdriver.io End to End Testing

---

src/providers/authenticationProvider.ts

This corrects the getTerraformCLIToken method to correctly find the TF credential file on Windows.

Fix finding TF credential file on windows

---

.github/SUPPORT.md
README.md
package.json
src/extension.ts
src/features/terraformCloud.ts
src/providers/authenticationProvider.ts
src/providers/tfc/organizationPicker.ts
src/terraformCloud/configurationVersion.ts
test/specs/extension.ts

This renames all user facing information containing the words "Terraform Cloud" to "HCP Terraform".
It does not rename/refactor any code using the old references. The authentication provider ID and sesison key remain the same to preserve existing logins.

Rename TFC to HCP Terraform

---

.github/workflows/issue-comment-created.yml

This PR replaces the unmaintained https://github.com/actions-ecosystem/action-remove-labels actions with a `gh` command.
This is part of the migration to Node 20 and should remove most of the warnings: https://github.com/hashicorp/vscode-terraform/actions/runs/8875007191

Replace outdated remove-labels action with `gh`

---

.github/workflows/test.yml
README.md
package-lock.json
package.json
src/features/languageStatus.ts
src/features/moduleCalls.ts
src/features/moduleProviders.ts
src/features/semanticTokens.ts
src/features/showReferences.ts
src/features/telemetry.ts
src/features/terraformVersion.ts
src/test/helper.ts

This updates the vscode-languageclient package to 9.0.1. This is a major update that includes a number of changes, including a new dependency on vscode-jsonrpc 8.2.0 and vscode-languageserver-protocol 3.17.5
NOTE: This requires bumping the minimum supported VS Code version to 1.86

Update vscode-languageclient to 9.0.1

---

.changes/unreleased/INTERNAL-20240523-135341.yaml
.copywrite.hcl
.vscodeignore

This change adds `.changie.yaml` and `.changes` to the `.vscodeignore` file so that they are not included in the VSIX package.
This was missed in https://github.com/hashicorp/vscode-terraform/pull/1757

Ignore changie logs in vsix by default

---

.changes/unreleased/INTERNAL-20240524-100633.yaml
.github/workflows/deploy.yml
.github/workflows/test.yml

This PR adds npm caching to the GitHub Actions workflows. This should speed up the CI builds by caching the npm packages between builds.

Cache npm packages in GitHub Actions

---

.changes/unreleased/INTERNAL-20240523-141243.yaml
package-lock.json
package.json
webpack.config.js

This commit uses esbuild-loader instead of ts-loader.
As part of our move to supporting web extensions, we moved from a pure esbuild configuration to a webpack based one. However the default TypeScript webpack bundler is slow compared to esbuild. We knew this when moving, but delayed figuring out how to use esbuild at a later date.
This commit uses esbuild-loader instead of ts-loader, which reduces build times from ~8-10 seconds to ~2-3 seconds. This benefits local development time as well as in CI. In CI we package 9 platforms, each taking over a minute to package. This now takes a few seconds for each platform.
This is a short term fix, as we plan to move to a pure esbuild configuration in the future.

Use esbuild with webpack

---

.changes/unreleased/BUG FIXES-20240606-104729.yaml
package.json

This will pull in the latest version of the language server with a small bug fix.
Since we now include the license file with each LS release, we extract two files into the `bin/` folder. But I don't see any problems with that.

Bump LS version to 0.33.2

---

.vscode/launch.json

This change updates the launch configuration to use a temporary profile
when launching the extension host. This is useful for debugging and developing the extension in an isolated environment from user settings.

Update launch config to use temp profile

---

.github/workflows/deploy.yml
build/preview.sh

This commit removes the preview script from the deploy workflow. The preview script is no longer needed as we use changie for incrementing the version number and will be committing the version number with prerelease as well as stable releases.

Remove preview script from deploy workflow

---

.changes/unreleased/ENHANCEMENTS-20240611-152455.yaml
build/downloader.ts
package.json

This begins the process of adding support for tfstack and tfdeploy files by declaring the file extensions and language identifiers in the package.json file. This will allow the extension to recognize these files and provide syntax highlighting and other language features. Future work will add icons and other features to fill out support.
Of particular note is the aliases used for tfstack.hcl and tfdeploy.hcl files. These aliases are used to provide a more user-friendly name for the language in the VS Code status bar and other places where the language name is displayed. Getting these aliases right is not only important from a branding perspective but also from a user experience perspective. They have to be readable and understandable in a small amount of space.

Declare support for Terraform Stacks

---

.changes/unreleased/ENHANCEMENTS-20240611-152345.yaml
assets/icons/terraform_stacks.svg
package.json

This adds a new file icon for the Stacks language which will apply to all tfstack.hcl and tfdeploy.hcl files.
This is a new icon for several reasons:
- The existing icon is not provided by HashiCorp, it is from the default VS Code icon theme Seti and releases to it are delivered in VS Code releases.
- We cannot reference it in our extension manifest, so we need to provide our own.
- We cannot override the Seti theme, [VS Code does not allow this](https://code.visualstudio.com/api/extension-guides/file-icon-theme#language-default-icons) and replace it.
Since this is not something we can control, we are providing our own icon to ensure we can deliver a consistent experience to our users.
To solve this a new icon was created that is similar in shape and size to the existing Seti Terraform …

Terraform Stacks Icons

---

src/api/terraformCloud/index.ts
src/api/terraformCloud/instance.ts
src/providers/tfc/authenticationProvider.ts

This is a simplified version of PR #1673 , as requested
This closes #1671  and closes #1505
Allow TFC host selection during login. Hosts already in TFC credentials file are displayed. Options for insertion of new hosts added:
N.B. Logging to a new hostname does not update the TFC credentials file (Maybe to be implemented in the future?)

Prompt for custom tfcloud host

---

src/extension.ts

This change adds document selectors for the Terraform Stacks and Terraform Deployments languages. This will enable the Language Server Protocol (LSP) for these languages.

Enable LSP for Terraform Stacks and Deployments

---

.changes/unreleased/INTERNAL-20240712-130524.yaml
.github/workflows/check-changelog.yml

This workflow checks for the adding or modification of files in the `.changie/unreleased` folder.
You can see it working for this PR
- The jobs fails for the first commit: https://github.com/hashicorp/vscode-terraform/actions/runs/9906849460/job/27369283073?pr=1796
- After adding a changelog entry, it passes: https://github.com/hashicorp/vscode-terraform/actions/runs/9906870191/job/27369345883?pr=1796

Introduce a workflow that checks for changelog entries

---

.changes/unreleased/ENHANCEMENTS-20240715-175145.yaml
src/test/integration/stacks/deployment.test.ts
src/test/integration/stacks/stack.test.ts
src/test/integration/stacks/workspace/deployments.tfdeploy.hcl

This was recently renamed in the agent.

Rename `variables` to `inputs` for Stack deployments

---

.changes/unreleased/INTERNAL-20240724-124159.yaml
.vscode/launch.json

This commit adds a new launch target to the launch.json file that allows you to run the extension in a development environment.
This is useful for debugging and testing the extension without using a temporary profile.

Add develop launch target for extensionHost

---

.changes/unreleased/BUG FIXES-20240808-105000.yaml
.changes/unreleased/ENHANCEMENTS-20240716-094842.yaml
.changes/unreleased/ENHANCEMENTS-20240717-114614.yaml
.changes/unreleased/ENHANCEMENTS-20240724-122601.yaml
.changes/unreleased/ENHANCEMENTS-20240725-163756.yaml
.changes/unreleased/ENHANCEMENTS-20240731-152949.yaml
.changes/unreleased/ENHANCEMENTS-20240731-155657.yaml
.changes/unreleased/ENHANCEMENTS-20240805-140526.yaml
.changes/unreleased/INTERNAL-20240717-115636.yaml
.changes/unreleased/INTERNAL-20240807-132909.yaml
package.json
src/test/integration/stacks/deployment.test.ts
src/test/integration/stacks/stack.test.ts

Needs https://github.com/hashicorp/terraform-ls/pull/1789 release

Bump terraform-ls from 0.34.2 to 0.35.0-alpha2

---

.changes/unreleased/ENHANCEMENTS-20240905-143313.yaml
src/status/language.ts

This commit enables the language status bar for the `terraform-stack` and `terraform-deploy` languages.

Enable langauge status bar for Stack languages

---

.changes/unreleased/ENHANCEMENTS-20240912-115949.yaml
src/extension.ts

* Requires https://github.com/hashicorp/terraform-ls/pull/1782
This PR adds Terraform Test & Mock file support. It adds the language configuration for test and mock files and registers the document selectors, so test files are picked up by the language server.

Static schema support for Terraform Test and Mock files

---

.changes/unreleased/BUG FIXES-20240924-094740.yaml
package.json

This commit updates the syntax version to 0.7.1, which fixes parsing expressions containing an open curly brace as blocks in https://github.com/hashicorp/syntax/pull/149

Bump syntax version to 0.7.1

---

.changes/unreleased/BUG FIXES-20241015-153342.yaml
src/test/integration/stacks/stack.test.ts

This PR fixes the test failure on `main`

Add `removed` block to Stack tests

---

.changes/unreleased/INTERNAL-20241016-132945.yaml
src/test/integration/stacks/deployment.test.ts
src/test/integration/stacks/stack.test.ts

This PR enables / completes the skipped tests for `.tfstack.hcl` and `.tfdeploy.hcl` files

Enable integration tests for Stacks feature

---

.changes/unreleased/INTERNAL-20241115-115811.yaml
.vscode/extensions.json

This extension is no longer needed as we are using esbuild for our build process.

Remove webpack extension recommendation

---

.changes/unreleased/INTERNAL-20241204-105834.yaml
package.json

This broadens the range of npm versions that are allowed to be used with this project. This is to allow for the use of npm 9.6.5, which is the version that dependabot is currently using.
This fixes the following dependabot error:
updater | npm ERR! code EBADENGINE
updater | npm ERR! engine Unsupported engine
updater | npm ERR! engine Not compatible with your version of node/npm: terraform@2.34.0
updater | npm ERR! notsup Not compatible with your version of node/npm: terraform@2.34.0
updater | npm ERR! notsup Required: {"npm":"~10.X","node":"~20.X","vscode":"^1.92.2"}
updater | npm ERR! notsup Actual:   {"npm":"9.6.5","node":"v20.18.1"}

Fix dependabot npm version

---

.changes/unreleased/BUG FIXES-20241204-121924.yaml
src/api/terraformCloud/index.ts
src/providers/tfc/workspaceProvider.ts

The `self-html` link for a workspace starts with `/app` so we need to use the base URL for Terraform Cloud to construct the full URL.

(IPL-7500) Fix HCP workspace link

---

.changes/unreleased/INTERNAL-20241209-123718.yaml
.github/workflows/test.yml

This PR updates the CI configuration for Ubuntu 24.04.1. GitHub has recently updated the latest ubuntu runners from 22.04.5 to 24.04.1.
This new command is required to successfully run our extension UI tests.

Fix tests on ubuntu

---

.changes/unreleased/INTERNAL-20241209-100936.yaml
.github/dependabot.yml

This bumps the versioning strategy to increase-if-necessary to allow for minor and patch updates to be automatically applied by Dependabot inside the package.json file. Our semantic version constraints are still respected with increase-if-necessary, but allows us to keep pace with libraries. See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy for more information.
This does introduce the possibility of breaking changes, as increase-if-necessary will update a major version. However since all PRs require a review, we can catch these breaking changes before they become a problem. We can monitor this and adjust the strategy if necessary.
Previously the versioning strategy was set to …

Configure dependabot to update package.json and group dependency updates

---

.changes/unreleased/INTERNAL-20241205-163130.yaml
.github/workflows/test.yml
.gitignore
.vscode-test.mjs
package.json

This enables code coverage reporting for the integration test suites. It uses the `vscode-test` extension's built-in code coverage reporting feature to generate coverage reports for the test suites.
Previously if you were to run `npm run compile` or `npm test`, you would be executing `npm run check-types`, then `npm run lint`, and finally `node esbuild.mjs` or `vscode-test`, respectively, every time you wanted to compile or test the code. This duplication added several seconds to the build or test time. This was unecessary when running interactively, and even more so in CI where these steps were repeated multiple times.
This also reduces the number of duplicate steps in CI by running type checking, linting, and formatting only once before compiling or running tests. It also results in a …

(TFECO-8268) Enable code coverage reporting

---

.changes/unreleased/INTERNAL-20241216-104206.yaml
src/test/e2e/specs/views/hcp.e2e.ts

This test was failing on macOS because the sleep time was too short. Increasing it to 500ms should be enough to make the test pass.

Fix flaky test by increasing sleep time

---

.changes/v2.34.3.md
CHANGELOG.md
package-lock.json
package.json

This brings the prerelease channel to parity with stable.
It also updates the changelog with a missing entry for 2.34.3.

Stage 2.34.2025012311

---

.changes/unreleased/INTERNAL-20250516-144118.yaml
package-lock.json
package.json
src/test/e2e/specs/views/hcp.e2e.ts

This commit updates the `vscode-extension-tester` package to version 8.14.1 and modifies the HCP view tests to ensure compatibility with the latest changes in VS Code insiders.

Update vscode-extension-tester to 8.14.1 and fix HCP view tests for VS Code insiders

---

.changes/unreleased/BUG FIXES-20250519-122303.yaml
src/commands/generateBugReport.ts
src/features/languageStatus.ts
src/features/moduleCalls.ts
src/features/moduleProviders.ts
src/features/showReferences.ts
src/features/telemetry.ts
src/features/terraformVersion.ts
src/providers/terraform/moduleCalls.ts
src/providers/tfc/applyProvider.ts
src/providers/tfc/planProvider.ts

1.  Fixing below linting error which:
Prefer using nullish coalescing operator (`??=`) instead of an assignment expression, as it is simpler to read  @typescript-eslint/prefer-nullish-coalescing
Documentation - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_assignment
2. Some code snippets were automatically formatted on file save (using prettier extension)

fix: linting errors related to nullish coalescing

---

.changes/unreleased/ENHANCEMENTS-20250917-154150.yaml
README.md

Update `README.md` following #2113. Closes #2120.

Update documention for MCP server integration
