hashicorp/vscode-terraform

package.json
Come for the syntax highlighting - stay for the linting, validation and formatting! 😛 
This makes the this plugin's search result much more appealing to those browsing for a Terraform plugin to do the primary functionality.
* **Before**: A cool little plugin for editing Hashicorp's Terraform files
* **After**: Syntax highlighting, linting, formatting, and validation for Hashicorp's Terraform
=> Better description for viewing in the extension marketplace

syntaxes/terraform.json, templates/template.tf
Fix issues listed above in one pull request. I have copied code from #24 and added request template example. This needs a new release.
=> Fix following issues in main repository #23, #26, #29

package.json
=> Mark tfstate files as JSON files

CHANGELOG.md, README.md, package-lock.json, package.json, src/extension.ts, src/format.ts, src/helpers.ts, src/providers.ts
=> Use the correct formatting contribution point

CHANGELOG.md, package.json, src/extension.ts, src/format.ts
=> Bring back format on autosave

syntaxes/terraform.json
This PR fixes #109 - encountered it today while switching from Atom to VS Code and thought I give it a try. I'm not an expert in the syntax so let's improve it together.
=> Fixed broken multiline strings

src/index/crawler.ts
This is an attempt to fix the issue I reported in https://github.com/mauve/vscode-terraform/issues/153
Before this PR, initial workspace indexing correctly skips files excluded in the configuration, this PR just makes the initial indexing run skip them significantly faster. 
The initial indexing run through for a workspace currently queues up all `.tf/.tfvars` files in the workspace for indexing, and relies on the lower level indexing logic to exit early if the URI matches on of the configured Excludes globs. 
However, it appears that the act of asynchronously dispatching each of those function calls generates a large amount of overhead for workspaces with large numbers of `.tf` files, even though those function calls should return very quickly themselves. 
This PR duplicates the …
=> Exclude configured directories from indexing during initial index run through.

.vscode/tasks.json, package.json, syntaxes/terraform.codeblock.json
=> Add support for terraform block in markdown files

src/languageServerInstaller.ts
=> Delete existing ls binary before unpacking upgrade

package.json
=> Enable syntax highlighting for tfvars

syntaxes/terraform.tmGrammar.json
=> Add syntax for object and tuple structural types

README.md
=> Fix default args for LS

syntaxes/terraform.tmGrammar.json
=> Fix block syntax labels

syntaxes/terraform.tmGrammar.json
=> Fix syntax highlighting for object expressions

CHANGELOG.md, package-lock.json, package.json, src/extension.ts, src/languageServerInstaller.ts
This restores behavior that was lost after #444
=> Delete downloaded zips

syntaxes/terraform.tmGrammar.json
=> Fix object key syntax highlighting

syntaxes/terraform.tmGrammar.json
=> Fix additional object key matching issues

package.json
add bugs/support email to package defs
=> Add support email to package configuration

src/test/symbols.test.ts
This reflects recent changes on the language server side.
=> Fix test data for symbols

package-lock.json, package.json, src/extension.ts
Closes https://github.com/hashicorp/terraform-ls/issues/297
=> Use short unique id to prevent command name collision

src/languageServerInstaller.ts
=> Read LS version from stdout

package.json, src/extension.ts
- Boolean: validateOnSave
Closes #534
=> Add setting for experimental features

package.json, src/extension.ts
=> Add terraform validate command

package-lock.json, package.json
Ref: https://github.com/actions/setup-node/issues/214
=> Update js-releases dep to fix build on GitHub Actions

src/languageServerInstaller.ts
=> Cancel language server install when upgrade message is closed

src/extension.ts
=> Add stopClient and execWorkspaceCommand telemetry events

src/languageServerInstaller.ts
Filter and log unexpected error types
=> Rescue version check errors on language server install

src/extension.ts
A couple of changes that might help us get more visibility into errors.
=> Update client telemetry

src/extension.ts, src/languageServerInstaller.ts
Fixes problems on some Windows environments
=> Normalize language server installer file paths

package-lock.json, package.json, src/extension.ts, src/test/symbols.test.ts, src/test/workspaces.test.ts, testFixture/sample.tf
Pending https://github.com/hashicorp/terraform-ls/pull/508
Closes #632
=> Rename rootModules command to module.callers

src/extension.ts
=> Avoid launching more servers if server supports multiple folders

src/extension.ts
=> Avoid duplicate language clients for non-multi-folder setup

package-lock.json, package.json, src/extension.ts
To add completion/hover/highlighting on tfvars (variable files).
Fixes #426
=> Add support for `tfvars` files

README.md
See also https://github.com/hashicorp/vscode-terraform/issues/687#issuecomment-881299036
=> Readme: Mention tip about default formatter

src/clientHandler.ts, src/showReferences.ts
Closes https://github.com/hashicorp/vscode-terraform/issues/651
Requires https://github.com/hashicorp/terraform-ls/pull/584
=> Register command to show references

README.md
Updating the list/documentation as suggested by a user on VS Code Marketplace:
=> Readme: Update known issues

package.json, src/clientHandler.ts
* terraformExecPath
* terraformExecTimeout
* terraformExecLogFilePath
Closes (partially) https://github.com/hashicorp/terraform-ls/issues/240
=> src/clientHandler: add support for certain CLI options

src/clientHandler.ts, src/extension.ts, src/vscodeUtils.ts
=> fix: avoid considering output panes as editors

package-lock.json, package.json
result of `npm version 2.15.0`
=> Bump version to 2.15.0 (prepare for release)

package.json, src/commands/generateBugReport.ts, src/extension.ts
Add a new command that records information from the current environment and generates a nicely formatted Github issue.
=> Generate bug report command

README.md
This updates the telemetry configuration information with the current settings and values as described in https://code.visualstudio.com/docs/getstarted/telemetry#_disable-telemetry-reporting.
=> Update telemetry configuration information

package-lock.json, package.json, src/clientHandler.ts, src/extension.ts, src/telemetry.ts
The telemetry package was renamed to @vscode/extension-telemetry
=> Update to @vscode/extension-telemetry

package.json
This is to address the following errors reported by VS Code on activation
=> Add missing descriptions to semantic token types & modifiers

package.json
Related to https://github.com/hashicorp/terraform-ls/issues/704
=> Deprecate terraform-ls.rootmodule and terraform-ls.excludeRootModules

.vscode/settings.json
This updates the Markdown language settings inside this project with the new setting values
=> Update new Markdown language Settings

src/extension.ts, src/handlers/errorHandler.ts
This adds telemetry for exceptions that occur during initialization and when there is a exception thrown by the language client.
=> Improve error telemetry

.github/workflows/preview.yml, .github/workflows/publish.yml, build/downloader.ts
This enables publishing web extensions in CI
=> Enable publishing web extensions

package-lock.json, package.json
As of v 2.15.0 vsce has been changed to @vscode/vsce.
=> Update vsce to @vscode/vsce

package.json
Depends on:
- https://github.com/hashicorp/hcl-lang/pull/232
- https://github.com/hashicorp/terraform-ls/pull/1233
=> package.json: Introduce semantic token for function

CHANGELOG.md, package.json
This will be published as part of the next preview release.
=> Update changelog & bump LS to 0.31.0-beta

package-lock.json, package.json
Closes https://github.com/hashicorp/vscode-terraform/issues/1387
=> Update vscode-languageclient to 8.1.0

package.json, src/features/terraformCloud.ts, src/providers/tfc/runProvider.ts, src/terraformCloud/run.ts
Implements parts of https://github.com/hashicorp/vscode-terraform/issues/1395
=> Implement basic TreeView provider for TFC runs

src/providers/tfc/helpers.ts, src/providers/tfc/runProvider.ts, src/providers/tfc/workspaceProvider.ts, src/terraformCloud/index.ts, src/terraformCloud/run.ts
Closes https://github.com/hashicorp/vscode-terraform/issues/1458
=> Polish run tree view

src/providers/tfc/helpers.ts, src/providers/tfc/workspaceProvider.ts
This adds run status icons and human readable text to the workspace hover and adds [] to the projectName in the description
=> Design feedback

src/extension.ts, src/features/terraformCloud.ts, src/providers/authenticationProvider.ts, src/providers/tfc/organizationPicker.ts, src/providers/tfc/runProvider.ts, src/providers/tfc/uiHelpers.ts, src/providers/tfc/workspaceFilters.ts, src/providers/tfc/workspaceProvider.ts, src/terraformCloud/account.ts, src/terraformCloud/errors.ts, src/terraformCloud/organization.ts, src/terraformCloud/project.ts, src/terraformCloud/run.ts, src/terraformCloud/workspace.ts
In addition to the UX changes shown below, all errors except for 401 and 404 are being logged now. I expect there will be more user-triggered errors we may want to exclude as we can do nothing to prevent them, but this is best effort for now.
=> TFC: Improve error handling

package.json, src/providers/tfc/workspaceProvider.ts, src/terraformCloud/workspace.ts
This PR improve the quality of life when working with larger projects with many workspaces.
See commits for individual changes
=> TFC workspaces improvements

package.json, src/features/terraformCloud.ts
- Add icon and 'TFC' prefix to statusBarItem text
- Add organization name to Workspace view title
- Add button to Workspace view to select organization
=> TFC organization icon

.github/ISSUE_TEMPLATE/performance.yml
This is mostly a copy-paste of the bug report issue template with a couple of questions removed that don't seem relevant.
=> Add new performance issue template

package.json
* Depends on https://github.com/hashicorp/terraform-ls/pull/1574
* Depends on https://github.com/hashicorp/hcl-lang/pull/362
=> Rename `hcl-traversalStep` to `hcl-referenceStep`

CHANGELOG.md, package-lock.json, package.json
* Depends on the 0.33.0 LS release https://github.com/hashicorp/terraform-ls/pull/1684
=> Release 2.30.0

package-lock.json, package.json, src/test/integration/mocks/server.ts
Hi! I know you are using MSW so I decided to update your stack to the latest 2.0 version of the library. That version introduces a bunch of improvements and bug fixes, as well as brings MSW closer to the platform since it now relies on the standard Fetch API primitives. 
Let me know in case I missed anything!
=> Update MSW to 2.0

.vscodeignore
Update .vscodeignore to exclude internal files
=> Update .vscodeignore exclusions

.changie.yaml
Update changie config to include auto versioning for INTERNAL and NOTES
=> Update changie config for auto versioning

.changes/unreleased/BUG FIXES-20240606-104729.yaml, .changes/unreleased/INTERNAL-20240523-135341.yaml, .changes/unreleased/INTERNAL-20240523-135953.yaml, .changes/unreleased/INTERNAL-20240523-140044.yaml, .changes/unreleased/INTERNAL-20240523-141243.yaml, .changes/unreleased/INTERNAL-20240524-100633.yaml, .changes/unreleased/INTERNAL-20240529-105916.yaml, .changes/v2.30.2.md, CHANGELOG.md, package-lock.json, package.json
_Automatically generated by running `npm run changelog:build`_
=> Stage 2.30.2

.changes/unreleased/ENHANCEMENTS-20240611-133948.yaml, .changes/v2.31.2024061114.md, CHANGELOG.md, package-lock.json, package.json
- **Bump terraform-ls from 0.33.2 to 0.34.0-alpha20240611**
- **Increment to next minor in preparation for prerelease**
- **Release 2.31.2024061114**
=> Release 2.31.2024061114

.changes/unreleased/BUG FIXES-20240823-102914.yaml, .changes/unreleased/ENHANCEMENTS-20240815-110018.yaml, .changes/unreleased/ENHANCEMENTS-20240815-121707.yaml, .changes/unreleased/ENHANCEMENTS-20240815-121709.yaml, .changes/unreleased/ENHANCEMENTS-20240815-121711.yaml, .changes/unreleased/ENHANCEMENTS-20240815-121714.yaml, .changes/unreleased/ENHANCEMENTS-20240815-121716.yaml, .changes/unreleased/ENHANCEMENTS-20240815-121718.yaml, .changes/unreleased/ENHANCEMENTS-20240815-121720.yaml, .changes/unreleased/ENHANCEMENTS-20240815-121722.yaml, .changes/unreleased/ENHANCEMENTS-20240815-121724.yaml, .changes/unreleased/ENHANCEMENTS-20240815-135108.yaml, .changes/unreleased/ENHANCEMENTS-20240816-134804.yaml, .changes/unreleased/ENHANCEMENTS-20240816-154910.yaml, .changes/unreleased/ENHANCEMENTS-20240823-102940.yaml, .changes/unreleased/ENHANCEMENTS-20240823-103027.yaml, .changes/unreleased/ENHANCEMENTS-20240823-103059.yaml, package.json, src/test/integration/stacks/stack.test.ts
Needs https://github.com/hashicorp/terraform-ls/pull/1806 release
=> Bump terraform-ls to 0.35.0-beta1

.changes/unreleased/BUG FIXES-20240823-102914.yaml, .changes/unreleased/ENHANCEMENTS-20240815-110018.yaml, .changes/unreleased/ENHANCEMENTS-20240815-121707.yaml, .changes/unreleased/ENHANCEMENTS-20240815-121709.yaml, .changes/unreleased/ENHANCEMENTS-20240815-121711.yaml, .changes/unreleased/ENHANCEMENTS-20240815-121714.yaml, .changes/unreleased/ENHANCEMENTS-20240815-121716.yaml, .changes/unreleased/ENHANCEMENTS-20240815-121718.yaml, .changes/unreleased/ENHANCEMENTS-20240815-121720.yaml, .changes/unreleased/ENHANCEMENTS-20240815-121722.yaml, .changes/unreleased/ENHANCEMENTS-20240815-121724.yaml, .changes/unreleased/ENHANCEMENTS-20240815-135108.yaml, .changes/unreleased/ENHANCEMENTS-20240816-134804.yaml, .changes/unreleased/ENHANCEMENTS-20240816-154910.yaml, .changes/unreleased/ENHANCEMENTS-20240823-102940.yaml, .changes/unreleased/ENHANCEMENTS-20240823-103027.yaml, .changes/unreleased/ENHANCEMENTS-20240823-103059.yaml, .changes/v2.33.2024082314.md, CHANGELOG.md, package-lock.json, package.json
Depends on https://github.com/hashicorp/vscode-terraform/pull/1826
=> Release 2.33.2024082314

.changes/unreleased/ENHANCEMENTS-20240923-174416.yaml, src/status/language.ts
Add terraform-test and terraform-mock to status bar items
=> Add terraform-test and terraform-mock to status bar items

.changes/unreleased/BUG FIXES-20240910-111438.yaml, .changes/unreleased/BUG FIXES-20240924-094740.yaml, .changes/unreleased/ENHANCEMENTS-20240912-115949.yaml, .changes/unreleased/ENHANCEMENTS-20240923-174416.yaml, .changes/v2.33.0.md, CHANGELOG.md, package-lock.json, package.json
- **Bump terraform-ls from 0.35.0-beta2 to 0.35.0**
- **Stage 2.33.0 release**
=> Stage 2.33.0

.changes/unreleased/INTERNAL-20241120-134025.yaml, META.d/_summary.yml, META.d/data.yml
This change adds the metadata for the internal Heimdall service to the repository.
=> (TFECO-8260) Add Heimdall metadata

.changes/v2.34.3.md, CHANGELOG.md, package-lock.json, package.json
Needs https://github.com/hashicorp/terraform-ls/pull/1933
=> Stage 2.34.3

.changes/unreleased/ENHANCEMENTS-20250701-174433.yaml, .changes/unreleased/INTERNAL-20250630-112312.yaml, .changes/v2.35.0.md, CHANGELOG.md, package-lock.json, package.json
=> Release 2.35.0

.changes/unreleased/ENHANCEMENTS-20250821-185355.yaml, .changes/unreleased/INTERNAL-20250828-155200.yaml, .changes/v2.36.0.md, CHANGELOG.md, package-lock.json, package.json
=> Release 2.36.0

.changes/unreleased/ENHANCEMENTS-20250915-111345.yaml, .changes/unreleased/ENHANCEMENTS-20250917-154150.yaml, .changes/v2.36.4.md, CHANGELOG.md, package-lock.json, package.json
=> Release 2.36.4

.changes/unreleased/ENHANCEMENTS-20250919-134258.yaml, package.json
Supports static schemas for terraform action. Bumped terraform-schema version
- https://github.com/hashicorp/terraform-schema/pull/477
- https://github.com/hashicorp/terraform-ls/pull/2031
=> Added Support for Terraform Action Static Schema

.changes/unreleased/ENHANCEMENTS-20250919-134258.yaml, .changes/v2.37.0.md, CHANGELOG.md, package-lock.json, package.json
=> Release 2.37.0

.changes/unreleased/INTERNAL-20250922-163045.yaml, .changes/v2.37.1.md, CHANGELOG.md, package-lock.json, package.json
=> Release 2.37.1

.changes/unreleased/NOTES-20250924-113426.yaml, README.md
=> docs(readme): Added: documentation for Terraform Search

.changes/unreleased/NOTES-20250924-113426.yaml, .changes/v2.37.2.md, CHANGELOG.md, package-lock.json, package.json
=> Release 2.37.2

.changes/unreleased/ENHANCEMENTS-20251007-112602.yaml, .changes/v2.37.3.md, CHANGELOG.md, package-lock.json, package.json
=> Release 2.37.3
